/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ISourceOptions } from "@tsparticles/engine";
import { ParticlesPluginRegistrar } from "./initParticlesEngine";
export { ISourceOptions } from "@tsparticles/engine";
export { ParticlesPluginRegistrar } from "./initParticlesEngine";
export namespace Components {
    interface StencilParticles {
        "containerId"?: string;
        "init"?: ParticlesPluginRegistrar;
        "options"?: ISourceOptions;
        "url"?: string;
    }
}
declare global {
    interface HTMLStencilParticlesElement extends Components.StencilParticles, HTMLStencilElement {
    }
    var HTMLStencilParticlesElement: {
        prototype: HTMLStencilParticlesElement;
        new (): HTMLStencilParticlesElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-particles": HTMLStencilParticlesElement;
    }
}
declare namespace LocalJSX {
    interface StencilParticles {
        "containerId"?: string;
        "init"?: ParticlesPluginRegistrar;
        "options"?: ISourceOptions;
        "url"?: string;
    }

    interface StencilParticlesAttributes {
        "url": string;
        "containerId": string;
    }

    interface IntrinsicElements {
        "stencil-particles": Omit<StencilParticles, keyof StencilParticlesAttributes> & { [K in keyof StencilParticles & keyof StencilParticlesAttributes]?: StencilParticles[K] } & { [K in keyof StencilParticles & keyof StencilParticlesAttributes as `attr:${K}`]?: StencilParticlesAttributes[K] } & { [K in keyof StencilParticles & keyof StencilParticlesAttributes as `prop:${K}`]?: StencilParticles[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-particles": LocalJSX.IntrinsicElements["stencil-particles"] & JSXBase.HTMLAttributes<HTMLStencilParticlesElement>;
        }
    }
}
