import type { BundleInfo } from "../types.js";

export const bundles: BundleInfo[] = [
  {
    name: "@tsparticles/basic",
    description: "Minimal bundle. Includes: circle shape, move plugin, blend plugin, opacity/size/out-modes/paint updaters, hex/hsl/rgb color support.",
    loadFunction: "loadBasic",
    packages: [
      "@tsparticles/plugin-blend",
      "@tsparticles/plugin-hex-color",
      "@tsparticles/plugin-hsl-color",
      "@tsparticles/plugin-rgb-color",
      "@tsparticles/plugin-move",
      "@tsparticles/shape-circle",
      "@tsparticles/updater-paint",
      "@tsparticles/updater-opacity",
      "@tsparticles/updater-out-modes",
      "@tsparticles/updater-size",
    ],
  },
  {
    name: "@tsparticles/slim",
    description: "Standard bundle. Extends basic with interactivity, all external interactions (except cannon/drag/particle/pop/trail), particle interactions (attract, collisions, links), emoji/image/line/polygon/square/star shapes, life/rotate updaters.",
    loadFunction: "loadSlim",
    extends: "@tsparticles/basic",
    packages: [
      "@tsparticles/basic",
      "@tsparticles/plugin-interactivity",
      "@tsparticles/plugin-easing-quad",
      "@tsparticles/interaction-external-attract",
      "@tsparticles/interaction-external-bounce",
      "@tsparticles/interaction-external-bubble",
      "@tsparticles/interaction-external-connect",
      "@tsparticles/interaction-external-destroy",
      "@tsparticles/interaction-external-grab",
      "@tsparticles/interaction-external-parallax",
      "@tsparticles/interaction-external-pause",
      "@tsparticles/interaction-external-push",
      "@tsparticles/interaction-external-remove",
      "@tsparticles/interaction-external-repulse",
      "@tsparticles/interaction-external-slow",
      "@tsparticles/interaction-particles-attract",
      "@tsparticles/interaction-particles-collisions",
      "@tsparticles/interaction-particles-links",
      "@tsparticles/shape-emoji",
      "@tsparticles/shape-image",
      "@tsparticles/shape-line",
      "@tsparticles/shape-polygon",
      "@tsparticles/shape-square",
      "@tsparticles/shape-star",
      "@tsparticles/updater-life",
      "@tsparticles/updater-rotate",
    ],
  },
  {
    name: "tsparticles",
    description: "Full bundle. Extends slim with absorbers, emitters, drag/trail interactions, extra updaters (destroy, roll, tilt, twinkle, wobble), text shape.",
    loadFunction: "loadFull",
    extends: "@tsparticles/slim",
    packages: [
      "@tsparticles/slim",
      "@tsparticles/plugin-absorbers",
      "@tsparticles/plugin-emitters",
      "@tsparticles/plugin-emitters-shape-circle",
      "@tsparticles/plugin-emitters-shape-square",
      "@tsparticles/interaction-external-drag",
      "@tsparticles/interaction-external-trail",
      "@tsparticles/updater-destroy",
      "@tsparticles/updater-roll",
      "@tsparticles/updater-tilt",
      "@tsparticles/updater-twinkle",
      "@tsparticles/updater-wobble",
      "@tsparticles/shape-text",
    ],
  },
  {
    name: "@tsparticles/all",
    description: "Everything bundle. Extends full with all plugins (export, infection, background-mask, canvas-mask, manual-particles, motion, poisson, polygon-mask, responsive, sounds, themes, trail, zoom), all easing, all colors, all shapes, all effects, all paths, extra interactions, extra emitter shapes.",
    loadFunction: "loadAll",
    extends: "tsparticles",
    packages: [
      "tsparticles",
      "@tsparticles/plugin-export-image",
      "@tsparticles/plugin-export-json",
      "@tsparticles/plugin-export-video",
      "@tsparticles/plugin-infection",
      "@tsparticles/plugin-background-mask",
      "@tsparticles/plugin-canvas-mask",
      "@tsparticles/plugin-manual-particles",
      "@tsparticles/plugin-motion",
      "@tsparticles/plugin-poisson-disc",
      "@tsparticles/plugin-polygon-mask",
      "@tsparticles/plugin-responsive",
      "@tsparticles/plugin-sounds",
      "@tsparticles/plugin-themes",
      "@tsparticles/plugin-trail",
      "@tsparticles/plugin-zoom",
      "@tsparticles/interaction-external-cannon",
      "@tsparticles/interaction-external-particle",
      "@tsparticles/interaction-external-pop",
      "@tsparticles/interaction-light",
      "@tsparticles/interaction-particles-repulse",
      "@tsparticles/plugin-emitters-shape-canvas",
      "@tsparticles/plugin-emitters-shape-path",
      "@tsparticles/plugin-emitters-shape-polygon",
      ...["hex", "hsl", "rgb", "hsv", "hwb", "lab", "lch", "oklab", "oklch", "named"].map(
        (c) => `@tsparticles/plugin-${c}-color`,
      ),
      ...["back", "bounce", "circ", "cubic", "elastic", "expo", "gaussian", "linear", "quad", "quart", "quint", "sigmoid", "sine", "smoothstep"].map(
        (e) => `@tsparticles/plugin-easing-${e}`,
      ),
      ...["bubble", "filter", "particles", "shadow", "trail"].map((e) => `@tsparticles/effect-${e}`),
      ...["arrow", "cards", "cog", "gif", "heart", "infinity", "matrix", "path", "ribbon", "rounded-polygon", "rounded-rect", "spiral", "squircle"].map(
        (s) => `@tsparticles/shape-${s}`,
      ),
      "@tsparticles/updater-gradient",
      "@tsparticles/updater-orbit",
      ...["branches", "brownian", "curl-noise", "curves", "fractal-noise", "grid", "levy", "perlin-noise", "polygon", "random", "simplex-noise", "spiral", "svg", "zig-zag"].map(
        (p) => `@tsparticles/path-${p}`,
      ),
    ],
  },
  {
    name: "@tsparticles/confetti",
    description: "Confetti-focused bundle. Extends basic with emitters, motion plugin, decorative shapes, and celebration updaters.",
    loadFunction: "doInitPlugins",
    extends: "@tsparticles/basic",
    packages: [
      "@tsparticles/basic",
      "@tsparticles/plugin-motion",
      "@tsparticles/plugin-emitters",
      "@tsparticles/shape-cards",
      "@tsparticles/shape-heart",
      "@tsparticles/shape-image",
      "@tsparticles/shape-polygon",
      "@tsparticles/shape-square",
      "@tsparticles/shape-star",
      "@tsparticles/shape-emoji",
      "@tsparticles/updater-rotate",
      "@tsparticles/updater-life",
      "@tsparticles/updater-roll",
      "@tsparticles/updater-tilt",
      "@tsparticles/updater-wobble",
    ],
  },
  {
    name: "@tsparticles/fireworks",
    description: "Fireworks-focused bundle. Extends basic with line shape, emitters, sounds, and firework-related updaters.",
    loadFunction: "doInitPlugins",
    extends: "@tsparticles/basic",
    packages: [
      "@tsparticles/basic",
      "@tsparticles/shape-line",
      "@tsparticles/plugin-blend",
      "@tsparticles/plugin-emitters",
      "@tsparticles/plugin-emitters-shape-square",
      "@tsparticles/plugin-sounds",
      "@tsparticles/updater-rotate",
      "@tsparticles/updater-destroy",
      "@tsparticles/updater-life",
      "@tsparticles/updater-paint",
    ],
  },
  {
    name: "@tsparticles/particles",
    description: "Lightweight general particle system. Extends basic with interactivity, collisions, and links.",
    loadFunction: "doInitPlugins",
    extends: "@tsparticles/basic",
    packages: [
      "@tsparticles/basic",
      "@tsparticles/plugin-interactivity",
      "@tsparticles/interaction-particles-collisions",
      "@tsparticles/interaction-particles-links",
    ],
  },
  {
    name: "@tsparticles/ribbons",
    description: "Ribbons effect bundle. Extends basic with motion, emitters, ribbon shape, and life updater.",
    loadFunction: "doInitPlugins",
    extends: "@tsparticles/basic",
    packages: [
      "@tsparticles/basic",
      "@tsparticles/plugin-motion",
      "@tsparticles/plugin-emitters",
      "@tsparticles/plugin-emitters-shape-square",
      "@tsparticles/shape-ribbon",
      "@tsparticles/updater-life",
    ],
  },
  {
    name: "@tsparticles/pjs",
    description: "particles.js compatibility layer. Drop-in replacement for particles.js with full API compatibility. Wraps the full tsparticles bundle.",
    loadFunction: "doInitPlugins",
    extends: "tsparticles",
    packages: [
      "tsparticles",
      "@tsparticles/plugin-responsive",
    ],
  },
];
