// Auto-generated by scripts/extractNeedsPlugin.ts
// Generated on 2026-06-04
// Run: npx tsx scripts/extractNeedsPlugin.ts

export interface NeedsPluginEntry {
  optionKeys: string[];
  optionPaths: string[];
}

export const needsPluginMap: Record<string, NeedsPluginEntry> = {
  "@tsparticles/plugin-absorbers": {
    optionKeys: [],
    optionPaths: ["absorbers"],
  },
  "@tsparticles/plugin-background-mask": {
    optionKeys: [],
    optionPaths: ["backgroundMask"],
  },
  "@tsparticles/plugin-blend": {
    optionKeys: [],
    optionPaths: ["blend"],
  },
  "@tsparticles/plugin-canvas-mask": {
    optionKeys: [],
    optionPaths: ["canvasMask"],
  },
  "@tsparticles/plugin-emitters": {
    optionKeys: [],
    optionPaths: ["emitters"],
  },
  "@tsparticles/plugin-infection": {
    optionKeys: [],
    optionPaths: ["infection"],
  },
  "@tsparticles/plugin-manual-particles": {
    optionKeys: [],
    optionPaths: ["manualParticles"],
  },
  "@tsparticles/plugin-poisson-disc": {
    optionKeys: [],
    optionPaths: ["poisson"],
  },
  "@tsparticles/plugin-polygon-mask": {
    optionKeys: [],
    optionPaths: ["polygon"],
  },
  "@tsparticles/plugin-responsive": {
    optionKeys: [],
    optionPaths: ["responsive"],
  },
  "@tsparticles/plugin-sounds": {
    optionKeys: [],
    optionPaths: ["sounds"],
  },
  "@tsparticles/plugin-themes": {
    optionKeys: [],
    optionPaths: ["themes"],
  },
};
