import type { PackageInfo, PackageCatalog } from "../types.js";

const interactionExternal: PackageInfo[] = [
  { name: "@tsparticles/interaction-external-attract", description: "Attracts particles toward a mouse position or area", category: "interaction-external", loadFunction: "loadExternalAttractInteraction", optionKeys: ["interactivity.modes.attract"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-bounce", description: "Makes particles bounce off the mouse cursor", category: "interaction-external", loadFunction: "loadExternalBounceInteraction", optionKeys: ["interactivity.modes.bounce"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-bubble", description: "Creates a bubble effect around the mouse, enlarging nearby particles", category: "interaction-external", loadFunction: "loadExternalBubbleInteraction", optionKeys: ["interactivity.modes.bubble"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-cannon", description: "Fires particles from the click position like a cannon", category: "interaction-external", loadFunction: "loadExternalCannonInteraction", optionKeys: ["interactivity.modes.cannon"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/interaction-external-connect", description: "Draws lines connecting particles to the mouse cursor", category: "interaction-external", loadFunction: "loadExternalConnectInteraction", optionKeys: ["interactivity.modes.connect"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-destroy", description: "Destroys particles on mouse click/hover", category: "interaction-external", loadFunction: "loadExternalDestroyInteraction", optionKeys: ["interactivity.modes.destroy"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-drag", description: "Allows dragging particles with the mouse", category: "interaction-external", loadFunction: "loadExternalDragInteraction", optionKeys: ["interactivity.modes.drag"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["slim"] },
  { name: "@tsparticles/interaction-external-grab", description: "Creates a grabbing effect connecting mouse to nearby particles with lines", category: "interaction-external", loadFunction: "loadExternalGrabInteraction", optionKeys: ["interactivity.modes.grab"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-parallax", description: "Creates a parallax effect based on mouse position", category: "interaction-external", loadFunction: "loadExternalParallaxInteraction", optionKeys: ["interactivity.events.onHover.parallax"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-particle", description: "Spawns a new particle on click at the click position", category: "interaction-external", loadFunction: "loadExternalParticleInteraction", optionKeys: ["interactivity.modes.particle"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/interaction-external-pause", description: "Pauses/unpauses the animation on mouse hover", category: "interaction-external", loadFunction: "loadExternalPauseInteraction", optionKeys: ["interactivity.modes.pause"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-pop", description: "Pops particles away on mouse click", category: "interaction-external", loadFunction: "loadExternalPopInteraction", optionKeys: ["interactivity.modes.pop"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/interaction-external-push", description: "Adds new particles on mouse click", category: "interaction-external", loadFunction: "loadExternalPushInteraction", optionKeys: ["interactivity.modes.push"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-remove", description: "Removes particles on mouse click", category: "interaction-external", loadFunction: "loadExternalRemoveInteraction", optionKeys: ["interactivity.modes.remove"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-repulse", description: "Repulses particles away from the mouse cursor", category: "interaction-external", loadFunction: "loadExternalRepulseInteraction", optionKeys: ["interactivity.modes.repulse"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-slow", description: "Slows down particles near the mouse cursor", category: "interaction-external", loadFunction: "loadExternalSlowInteraction", optionKeys: ["interactivity.modes.slow"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-external-trail", description: "Creates a trail of particles following the mouse", category: "interaction-external", loadFunction: "loadExternalTrailInteraction", optionKeys: ["interactivity.modes.trail"], needsPluginCheck: "always when interactivity plugin loaded", alwaysNeeded: true, includedInBundles: ["slim"] },
];

const interactionParticles: PackageInfo[] = [
  { name: "@tsparticles/interaction-particles-attract", description: "Particles attract each other", category: "interaction-particles", loadFunction: "loadParticlesAttractInteraction", optionKeys: ["particles.move.attract"], needsPluginCheck: "always when loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/interaction-particles-collisions", description: "Particles bounce off each other on collision", category: "interaction-particles", loadFunction: "loadParticlesCollisionsInteraction", optionKeys: ["particles.collisions"], needsPluginCheck: "always when loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim", "particles"] },
  { name: "@tsparticles/interaction-particles-links", description: "Draws connecting lines between nearby particles", category: "interaction-particles", loadFunction: "loadParticlesLinksInteraction", optionKeys: ["particles.links"], needsPluginCheck: "always when loaded", alwaysNeeded: true, includedInBundles: ["basic", "slim", "particles"] },
  { name: "@tsparticles/interaction-particles-repulse", description: "Particles repulse each other", category: "interaction-particles", loadFunction: "loadParticlesRepulseInteraction", optionKeys: ["particles.move.repulse"], needsPluginCheck: "always when loaded", alwaysNeeded: true, includedInBundles: [] },
];

const interactionLight: PackageInfo[] = [
  { name: "@tsparticles/interaction-light", description: "Light interaction - particles react to a light source", category: "interaction-light", loadFunction: "loadLightInteraction", optionKeys: ["interactivity.modes.light"], needsPluginCheck: "always when loaded", alwaysNeeded: true, includedInBundles: [] },
];

const updaters: PackageInfo[] = [
  { name: "@tsparticles/updater-destroy", description: "Particle destruction effects (split, explode)", category: "updater", loadFunction: "loadDestroyUpdater", optionKeys: ["particles.destroy"], needsPluginCheck: "used when particles.destroy is set", alwaysNeeded: true, includedInBundles: ["slim", "fireworks"] },
  { name: "@tsparticles/updater-gradient", description: "Animate colors using gradients over time", category: "updater", loadFunction: "loadGradientUpdater", optionKeys: ["particles.gradient"], needsPluginCheck: "used when particles.gradient is set", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/updater-life", description: "Particle lifetime control (birth, death, duration)", category: "updater", loadFunction: "loadLifeUpdater", optionKeys: ["particles.life"], needsPluginCheck: "used when particles.life is set", alwaysNeeded: true, includedInBundles: ["slim", "confetti", "fireworks", "ribbons"] },
  { name: "@tsparticles/updater-opacity", description: "Animate particle opacity", category: "updater", loadFunction: "loadOpacityUpdater", optionKeys: ["particles.opacity"], needsPluginCheck: "used when particles.opacity.animation is set", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/updater-orbit", description: "Particles orbit around other particles or points", category: "updater", loadFunction: "loadOrbitUpdater", optionKeys: ["particles.orbit"], needsPluginCheck: "used when particles.orbit is set", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/updater-out-modes", description: "Out-of-bounds particle behavior (bounce, destroy, none, out)", category: "updater", loadFunction: "loadOutModesUpdater", optionKeys: ["particles.move.outModes"], needsPluginCheck: "essential for move behavior", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/updater-paint", description: "Paint/fill and stroke effects on particles", category: "updater", loadFunction: "loadPaintUpdater", optionKeys: ["particles.paint"], needsPluginCheck: "used when particles.paint is set", alwaysNeeded: true, includedInBundles: ["basic", "slim", "fireworks"] },
  { name: "@tsparticles/updater-roll", description: "Particle rolling effect (rotates with movement)", category: "updater", loadFunction: "loadRollUpdater", optionKeys: ["particles.roll"], needsPluginCheck: "used when particles.roll is set", alwaysNeeded: true, includedInBundles: ["slim", "confetti"] },
  { name: "@tsparticles/updater-rotate", description: "Animate particle rotation", category: "updater", loadFunction: "loadRotateUpdater", optionKeys: ["particles.rotate"], needsPluginCheck: "used when particles.rotate is set", alwaysNeeded: true, includedInBundles: ["slim", "confetti", "fireworks"] },
  { name: "@tsparticles/updater-size", description: "Animate particle size", category: "updater", loadFunction: "loadSizeUpdater", optionKeys: ["particles.size"], needsPluginCheck: "used when particles.size.animation is set", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/updater-tilt", description: "Particle tilt/3D rotation animation", category: "updater", loadFunction: "loadTiltUpdater", optionKeys: ["particles.tilt"], needsPluginCheck: "used when particles.tilt is set", alwaysNeeded: true, includedInBundles: ["slim", "confetti"] },
  { name: "@tsparticles/updater-twinkle", description: "Twinkle/sparkle effect on particles", category: "updater", loadFunction: "loadTwinkleUpdater", optionKeys: ["particles.twinkle"], needsPluginCheck: "used when particles.twinkle is set", alwaysNeeded: true, includedInBundles: ["slim"] },
  { name: "@tsparticles/updater-wobble", description: "Particle wobble/oscillation effect", category: "updater", loadFunction: "loadWobbleUpdater", optionKeys: ["particles.wobble"], needsPluginCheck: "used when particles.wobble is set", alwaysNeeded: true, includedInBundles: ["slim", "confetti"] },
];

const shapes: PackageInfo[] = [
  { name: "@tsparticles/shape-arrow", description: "Arrow shape for particles", category: "shape", loadFunction: "loadArrowShape", optionKeys: ["particles.shape.type", "particles.shape.options.arrow"], needsPluginCheck: "used when shape type is 'arrow'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-cards", description: "Playing card suits shape (hearts, diamonds, clubs, spades)", category: "shape", loadFunction: "loadCardSuitsShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'cards'", alwaysNeeded: false, includedInBundles: ["confetti"] },
  { name: "@tsparticles/shape-circle", description: "Circle shape - the default particle shape", category: "shape", loadFunction: "loadCircleShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "circle is the default shape", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/shape-cog", description: "Cog/gear shape for particles", category: "shape", loadFunction: "loadCogShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'cog'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-emoji", description: "Emoji/unicode character shape", category: "shape", loadFunction: "loadEmojiShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'emoji'", alwaysNeeded: false, includedInBundles: ["slim", "confetti"] },
  { name: "@tsparticles/shape-gif", description: "Animated GIF image shape", category: "shape", loadFunction: "loadGifShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'gif'", alwaysNeeded: false, includedInBundles: ["all"] },
  { name: "@tsparticles/shape-heart", description: "Heart shape for particles", category: "shape", loadFunction: "loadHeartShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'heart'", alwaysNeeded: false, includedInBundles: ["confetti"] },
  { name: "@tsparticles/shape-image", description: "Custom image shape - use any image URL as particle", category: "shape", loadFunction: "loadImageShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'image'", alwaysNeeded: false, includedInBundles: ["slim", "confetti"] },
  { name: "@tsparticles/shape-infinity", description: "Infinity symbol (∞) shape", category: "shape", loadFunction: "loadInfinityShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'infinity'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-line", description: "Line shape for particles", category: "shape", loadFunction: "loadLineShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'line'", alwaysNeeded: false, includedInBundles: ["slim", "fireworks"] },
  { name: "@tsparticles/shape-matrix", description: "Matrix code rain character shape", category: "shape", loadFunction: "loadMatrixShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'matrix'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-path", description: "Custom SVG path shape", category: "shape", loadFunction: "loadPathShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'path'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-polygon", description: "Regular polygon shape (triangle, pentagon, hexagon, etc.)", category: "shape", loadFunction: "loadPolygonShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'polygon'", alwaysNeeded: false, includedInBundles: ["slim", "confetti"] },
  { name: "@tsparticles/shape-ribbon", description: "Ribbon/banner shape", category: "shape", loadFunction: "loadRibbonShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'ribbon'", alwaysNeeded: false, includedInBundles: ["ribbons"] },
  { name: "@tsparticles/shape-rounded-polygon", description: "Rounded regular polygon shape", category: "shape", loadFunction: "loadRoundedPolygonShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'rounded-polygon'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-rounded-rect", description: "Rounded rectangle shape", category: "shape", loadFunction: "loadRoundedRectShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'rounded-rect'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-spiral", description: "Spiral shape", category: "shape", loadFunction: "loadSpiralShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'spiral'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-square", description: "Square/rectangle shape", category: "shape", loadFunction: "loadSquareShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'square'", alwaysNeeded: false, includedInBundles: ["slim", "confetti"] },
  { name: "@tsparticles/shape-squircle", description: "Squircle shape (square-circle hybrid)", category: "shape", loadFunction: "loadSquircleShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'squircle'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/shape-star", description: "Star shape with configurable points", category: "shape", loadFunction: "loadStarShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'star'", alwaysNeeded: false, includedInBundles: ["slim", "confetti"] },
  { name: "@tsparticles/shape-text", description: "Text/character shape", category: "shape", loadFunction: "loadTextShape", optionKeys: ["particles.shape.type"], needsPluginCheck: "used when shape type is 'text'", alwaysNeeded: false, includedInBundles: ["slim"] },
];

const plugins: PackageInfo[] = [
  { name: "@tsparticles/plugin-absorbers", description: "Absorber plugin - particles are absorbed into defined points", category: "plugin", loadFunction: "loadAbsorbersPlugin", optionKeys: ["absorbers"], needsPluginCheck: "options?.absorbers is defined", alwaysNeeded: false, includedInBundles: ["slim"] },
  { name: "@tsparticles/plugin-background-mask", description: "Background masking overlay effect", category: "plugin", loadFunction: "loadBackgroundMaskPlugin", optionKeys: ["backgroundMask"], needsPluginCheck: "options?.backgroundMask?.enable", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-blend", description: "CSS blend mode for particles", category: "plugin", loadFunction: "loadBlendPlugin", optionKeys: ["blend", "particles.blend"], needsPluginCheck: "options?.blend?.enable or options?.particles?.blend?.enable", alwaysNeeded: false, includedInBundles: ["basic", "fireworks"] },
  { name: "@tsparticles/plugin-canvas-mask", description: "Mask particles using an HTML canvas element", category: "plugin", loadFunction: "loadCanvasMaskPlugin", optionKeys: ["canvasMask"], needsPluginCheck: "options?.canvasMask?.enable", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-emitters", description: "Emitter plugin - spawn particles from defined points/areas", category: "plugin", loadFunction: "loadEmittersPlugin", optionKeys: ["emitters"], needsPluginCheck: "options?.emitters is array with length or defined", alwaysNeeded: false, includedInBundles: ["slim", "confetti", "fireworks", "ribbons"] },
  { name: "@tsparticles/plugin-export-image", description: "Export canvas as image (PNG/JPEG)", category: "plugin", loadFunction: "loadExportImagePlugin", optionKeys: ["export.image"], needsPluginCheck: "always", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/plugin-export-json", description: "Export particle positions as JSON", category: "plugin", loadFunction: "loadExportJSONPlugin", optionKeys: ["export.json"], needsPluginCheck: "always", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/plugin-export-video", description: "Export animation as video", category: "plugin", loadFunction: "loadExportVideoPlugin", optionKeys: ["export.video"], needsPluginCheck: "always", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/plugin-infection", description: "Infection/disease spread simulation between particles", category: "plugin", loadFunction: "loadInfectionPlugin", optionKeys: ["infection"], needsPluginCheck: "options?.infection?.enable", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-interactivity", description: "Core interactivity system (mouse/touch events)", category: "plugin", loadFunction: "loadInteractivityPlugin", optionKeys: ["interactivity"], needsPluginCheck: "always when interactivity is used", alwaysNeeded: true, includedInBundles: ["slim", "particles"] },
  { name: "@tsparticles/plugin-manual-particles", description: "Manually add particles to the canvas in code", category: "plugin", loadFunction: "loadManualParticlesPlugin", optionKeys: ["manualParticles"], needsPluginCheck: "options?.manualParticles?.length", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-motion", description: "Device motion/orientation support for particles", category: "plugin", loadFunction: "loadMotionPlugin", optionKeys: ["motion"], needsPluginCheck: "always", alwaysNeeded: true, includedInBundles: ["confetti", "ribbons"] },
  { name: "@tsparticles/plugin-move", description: "Core particle movement system", category: "plugin", loadFunction: "loadMovePlugin", optionKeys: ["particles.move"], needsPluginCheck: "always - required for particle movement", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/plugin-poisson-disc", description: "Poisson disc sampling for particle placement", category: "plugin", loadFunction: "loadPoissonDiscPlugin", optionKeys: ["poisson"], needsPluginCheck: "options?.poisson?.enable", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-polygon-mask", description: "Mask particles inside an SVG polygon", category: "plugin", loadFunction: "loadPolygonMaskPlugin", optionKeys: ["polygon"], needsPluginCheck: "options?.polygon?.enable or options?.polygon?.type !== none", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-responsive", description: "Responsive breakpoints for different screen sizes", category: "plugin", loadFunction: "loadResponsivePlugin", optionKeys: ["responsive"], needsPluginCheck: "options?.responsive?.length", alwaysNeeded: false, includedInBundles: ["pjs"] },
  { name: "@tsparticles/plugin-sounds", description: "Audio/sound effects triggered by particle events", category: "plugin", loadFunction: "loadSoundsPlugin", optionKeys: ["sounds"], needsPluginCheck: "options?.sounds?.enable", alwaysNeeded: false, includedInBundles: ["fireworks"] },
  { name: "@tsparticles/plugin-themes", description: "Dark/light theme support", category: "plugin", loadFunction: "loadThemesPlugin", optionKeys: ["themes"], needsPluginCheck: "options?.themes?.length", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-trail", description: "Particle trail effect - particles follow a path", category: "plugin", loadFunction: "loadTrailPlugin", optionKeys: ["trail"], needsPluginCheck: "always", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/plugin-zoom", description: "Zoom to particle effect on click/hover", category: "plugin", loadFunction: "loadZoomPlugin", optionKeys: ["interactivity.modes.zoom"], needsPluginCheck: "always", alwaysNeeded: true, includedInBundles: [] },
];

const colorPlugins: PackageInfo[] = [
  { name: "@tsparticles/plugin-hex-color", description: "Hexadecimal (#RRGGBB) color support", category: "color", loadFunction: "loadHexColorPlugin", optionKeys: [], needsPluginCheck: "always - essential color format", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/plugin-hsl-color", description: "HSL (hue/saturation/lightness) color support", category: "color", loadFunction: "loadHslColorPlugin", optionKeys: [], needsPluginCheck: "always - essential color format", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/plugin-rgb-color", description: "RGB/rgba color support", category: "color", loadFunction: "loadRgbColorPlugin", optionKeys: [], needsPluginCheck: "always - essential color format", alwaysNeeded: true, includedInBundles: ["basic", "slim"] },
  { name: "@tsparticles/plugin-hsv-color", description: "HSV (hue/saturation/value) color format support", category: "color", loadFunction: "loadHsvColorPlugin", optionKeys: [], needsPluginCheck: "optional color format", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-hwb-color", description: "HWB (hue/whiteness/blackness) color format support", category: "color", loadFunction: "loadHwbColorPlugin", optionKeys: [], needsPluginCheck: "optional color format", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-lab-color", description: "CIELAB color format support", category: "color", loadFunction: "loadLabColorPlugin", optionKeys: [], needsPluginCheck: "optional color format", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-lch-color", description: "LCH (lightness/chroma/hue) color format support", category: "color", loadFunction: "loadLchColorPlugin", optionKeys: [], needsPluginCheck: "optional color format", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-oklab-color", description: "OKLAB (perceptual) color format support", category: "color", loadFunction: "loadOklabColorPlugin", optionKeys: [], needsPluginCheck: "optional color format", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-oklch-color", description: "OKLCH (perceptual) color format support", category: "color", loadFunction: "loadOklchColorPlugin", optionKeys: [], needsPluginCheck: "optional color format", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-named-color", description: "Named CSS colors (red, blue, etc.) support", category: "color", loadFunction: "loadNamedColorPlugin", optionKeys: [], needsPluginCheck: "optional color format", alwaysNeeded: false, includedInBundles: [] },
];

const easingPlugins: PackageInfo[] = [
  { name: "@tsparticles/plugin-easing-back", description: "Back easing function", category: "easing", loadFunction: "loadEasingBackPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-bounce", description: "Bounce easing function", category: "easing", loadFunction: "loadEasingBouncePlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-circ", description: "Circular easing function", category: "easing", loadFunction: "loadEasingCircPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-cubic", description: "Cubic easing function", category: "easing", loadFunction: "loadEasingCubicPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-elastic", description: "Elastic easing function", category: "easing", loadFunction: "loadEasingElasticPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-expo", description: "Exponential easing function", category: "easing", loadFunction: "loadEasingExpoPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-gaussian", description: "Gaussian easing function", category: "easing", loadFunction: "loadEasingGaussianPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-linear", description: "Linear easing function", category: "easing", loadFunction: "loadEasingLinearPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-quad", description: "Quadratic easing function", category: "easing", loadFunction: "loadEasingQuadPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: ["slim"] },
  { name: "@tsparticles/plugin-easing-quart", description: "Quartic easing function", category: "easing", loadFunction: "loadEasingQuartPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-quint", description: "Quintic easing function", category: "easing", loadFunction: "loadEasingQuintPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-sigmoid", description: "Sigmoid easing function", category: "easing", loadFunction: "loadEasingSigmoidPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-sine", description: "Sine easing function", category: "easing", loadFunction: "loadEasingSinePlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-easing-smoothstep", description: "Smoothstep easing function", category: "easing", loadFunction: "loadEasingSmoothstepPlugin", optionKeys: [], needsPluginCheck: "used by animation easing options", alwaysNeeded: false, includedInBundles: [] },
];

const effects: PackageInfo[] = [
  { name: "@tsparticles/effect-bubble", description: "Bubble effect overlay", category: "effect", loadFunction: "loadBubbleEffect", optionKeys: ["effect"], needsPluginCheck: "used when effect type is 'bubble'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/effect-filter", description: "CSS filter effect overlay", category: "effect", loadFunction: "loadFilterEffect", optionKeys: ["effect"], needsPluginCheck: "used when effect type is 'filter'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/effect-particles", description: "Particles inside particles effect", category: "effect", loadFunction: "loadParticlesEffect", optionKeys: ["effect"], needsPluginCheck: "used when effect type is 'particles'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/effect-shadow", description: "Drop shadow effect on particles", category: "effect", loadFunction: "loadShadowEffect", optionKeys: ["effect"], needsPluginCheck: "used when effect type is 'shadow'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/effect-trail", description: "Motion trail effect for particles", category: "effect", loadFunction: "loadTrailEffect", optionKeys: ["effect"], needsPluginCheck: "used when effect type is 'trail'", alwaysNeeded: false, includedInBundles: [] },
];

const paths: PackageInfo[] = [
  { name: "@tsparticles/path-branches", description: "Branch-like path for particle movement", category: "path", loadFunction: "loadBranchesPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-brownian", description: "Brownian motion path generator", category: "path", loadFunction: "loadBrownianPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-curl-noise", description: "Curl noise path for organic fluid-like movement", category: "path", loadFunction: "loadCurlNoisePath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-curves", description: "Curved path generator", category: "path", loadFunction: "loadCurvesPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-fractal-noise", description: "Fractal noise path for complex natural movement", category: "path", loadFunction: "loadFractalNoisePath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-grid", description: "Grid-based path for particle movement", category: "path", loadFunction: "loadGridPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-levy", description: "Levy flight path for particle movement", category: "path", loadFunction: "loadLevyPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-perlin-noise", description: "Perlin noise path for smooth natural movement", category: "path", loadFunction: "loadPerlinNoisePath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-polygon", description: "Polygon path for particle movement", category: "path", loadFunction: "loadPolygonPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-random", description: "Random path generator", category: "path", loadFunction: "loadRandomPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-simplex-noise", description: "Simplex noise path for natural movement", category: "path", loadFunction: "loadSimplexNoisePath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-spiral", description: "Spiral path for particle movement", category: "path", loadFunction: "loadSpiralPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-svg", description: "SVG path for particle movement", category: "path", loadFunction: "loadSVGPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/path-zig-zag", description: "Zig-zag path for particle movement", category: "path", loadFunction: "loadZigZagPath", optionKeys: ["particles.move.path.options"], needsPluginCheck: "used in path generator", alwaysNeeded: false, includedInBundles: [] },
];

const emitterShapes: PackageInfo[] = [
  { name: "@tsparticles/plugin-emitters-shape-circle", description: "Circular emitter shape", category: "emitter-shape", loadFunction: "loadEmittersShapeCircle", optionKeys: ["emitters.shape.type"], needsPluginCheck: "used when emitter shape type is 'circle'", alwaysNeeded: false, includedInBundles: ["slim"] },
  { name: "@tsparticles/plugin-emitters-shape-square", description: "Square/rectangular emitter shape", category: "emitter-shape", loadFunction: "loadEmittersShapeSquare", optionKeys: ["emitters.shape.type"], needsPluginCheck: "used when emitter shape type is 'square'", alwaysNeeded: false, includedInBundles: ["slim", "fireworks", "ribbons"] },
  { name: "@tsparticles/plugin-emitters-shape-canvas", description: "Canvas-based custom emitter shape", category: "emitter-shape", loadFunction: "loadEmittersShapeCanvas", optionKeys: ["emitters.shape.type"], needsPluginCheck: "used when emitter shape type is 'canvas'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-emitters-shape-path", description: "Path-based emitter shape", category: "emitter-shape", loadFunction: "loadEmittersShapePath", optionKeys: ["emitters.shape.type"], needsPluginCheck: "used when emitter shape type is 'path'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/plugin-emitters-shape-polygon", description: "Polygon emitter shape", category: "emitter-shape", loadFunction: "loadEmittersShapePolygon", optionKeys: ["emitters.shape.type"], needsPluginCheck: "used when emitter shape type is 'polygon'", alwaysNeeded: false, includedInBundles: [] },
];

const bundles: PackageInfo[] = [
  { name: "@tsparticles/basic", description: "Minimal bundle - circle shape, move plugin, basic updaters, essential color formats", category: "bundle", loadFunction: "loadBasic", optionKeys: [], needsPluginCheck: "recommended as base for any project", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/slim", description: "Standard bundle - extends basic with interactivity, links, collisions, many shapes and updaters", category: "bundle", loadFunction: "loadSlim", optionKeys: [], needsPluginCheck: "recommended for most projects", alwaysNeeded: true, includedInBundles: [] },
  { name: "tsparticles", description: "Full bundle - extends slim with absorbers, emitters, drag/trail, more shapes and updaters", category: "bundle", loadFunction: "loadFull", optionKeys: [], needsPluginCheck: "use for advanced features", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/all", description: "Everything bundle - all plugins, shapes, updaters, paths, effects, easing", category: "bundle", loadFunction: "loadAll", optionKeys: [], needsPluginCheck: "use for maximum features", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/confetti", description: "Confetti-focused bundle with emitters, decorative shapes, and celebration effects", category: "bundle", loadFunction: "loadConfetti", optionKeys: [], needsPluginCheck: "use for confetti effects", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/fireworks", description: "Fireworks-focused bundle with emitters, sounds, and explosion effects", category: "bundle", loadFunction: "loadFireworks", optionKeys: [], needsPluginCheck: "use for fireworks effects", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/particles", description: "Lightweight general particle system with collisions and links", category: "bundle", loadFunction: "loadParticlesBundle", optionKeys: [], needsPluginCheck: "use for basic particle systems", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/ribbons", description: "Ribbon effects bundle with emitters and ribbon shapes", category: "bundle", loadFunction: "loadRibbonsBundle", optionKeys: [], needsPluginCheck: "use for ribbon effects", alwaysNeeded: true, includedInBundles: [] },
  { name: "@tsparticles/pjs", description: "particles.js compatibility shim (loads full + responsive)", category: "bundle", loadFunction: "initPjs", optionKeys: [], needsPluginCheck: "use for particles.js migration", alwaysNeeded: true, includedInBundles: [] },
];

const presets: PackageInfo[] = [
  { name: "@tsparticles/preset-ambient", description: "Ambient background particle effect preset", category: "preset", loadFunction: "loadAmbientPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'ambient'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-big-circles", description: "Big circles particle effect preset", category: "preset", loadFunction: "loadBigCirclesPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'big-circles'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-bubbles", description: "Bubbles effect preset", category: "preset", loadFunction: "loadBubblesPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'bubbles'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-confetti", description: "Confetti party effect preset", category: "preset", loadFunction: "loadConfettiPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'confetti'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-confetti-cannon", description: "Confetti cannon burst effect preset", category: "preset", loadFunction: "loadConfettiCannonPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'confetti-cannon'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-confetti-explosions", description: "Confetti explosions effect preset", category: "preset", loadFunction: "loadConfettiExplosionsPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'confetti-explosions'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-confetti-falling", description: "Falling confetti effect preset", category: "preset", loadFunction: "loadConfettiFallingPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'confetti-falling'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-confetti-parade", description: "Confetti parade effect preset", category: "preset", loadFunction: "loadConfettiParadePreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'confetti-parade'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-fire", description: "Fire/flame effect preset", category: "preset", loadFunction: "loadFirePreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'fire'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-firefly", description: "Firefly/glowing bug effect preset", category: "preset", loadFunction: "loadFireflyPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'firefly'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-fireworks", description: "Fireworks display effect preset", category: "preset", loadFunction: "loadFireworksPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'fireworks'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-fountain", description: "Fountain water effect preset", category: "preset", loadFunction: "loadFountainPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'fountain'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-hyperspace", description: "Hyperspace/star-warp effect preset", category: "preset", loadFunction: "loadHyperspacePreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'hyperspace'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-links", description: "Connected particles network effect preset", category: "preset", loadFunction: "loadLinksPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'links'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-matrix", description: "Matrix digital rain effect preset", category: "preset", loadFunction: "loadMatrixPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'matrix'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-meteors", description: "Meteors/shooting-star effect preset", category: "preset", loadFunction: "loadMeteorsPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'meteors'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-party", description: "Party celebration particles preset", category: "preset", loadFunction: "loadPartyPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'party'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-sea-anemone", description: "Sea anemone/underwater creature effect preset", category: "preset", loadFunction: "loadSeaAnemonePreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'sea-anemone'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-snow", description: "Snow falling effect preset", category: "preset", loadFunction: "loadSnowPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'snow'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-squares", description: "Square particles grid effect preset", category: "preset", loadFunction: "loadSquaresPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'squares'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-stars", description: "Twinkling stars effect preset", category: "preset", loadFunction: "loadStarsPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'stars'", alwaysNeeded: false, includedInBundles: [] },
  { name: "@tsparticles/preset-triangles", description: "Triangle mesh effect preset", category: "preset", loadFunction: "loadTrianglesPreset", optionKeys: ["preset"], needsPluginCheck: "use preset: 'triangles'", alwaysNeeded: false, includedInBundles: [] },
];

export const allPackages: PackageInfo[] = [
  ...interactionExternal,
  ...interactionParticles,
  ...interactionLight,
  ...updaters,
  ...shapes,
  ...plugins,
  ...colorPlugins,
  ...easingPlugins,
  ...effects,
  ...paths,
  ...emitterShapes,
  ...presets,
  ...bundles,
];

function buildCatalog(): PackageCatalog {
  const byCategory = {} as PackageCatalog["byCategory"];
  const byName: Record<string, PackageInfo> = {};

  for (const pkg of allPackages) {
    if (!byCategory[pkg.category]) {
      byCategory[pkg.category] = [];
    }
    byCategory[pkg.category].push(pkg);
    byName[pkg.name] = pkg;
  }

  return { byCategory, byName };
}

export const packageCatalog = buildCatalog();
