import type { OptionPluginMapping } from "../types.js";
import { needsPluginMap } from "./needsPluginMap.js";

function describePackage(name: string): string {
  return name
    .replace("@tsparticles/", "")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const autoGeneratedPackages = new Set(Object.keys(needsPluginMap));

// ── Auto-generated from plugin needsPlugin() (authoritative) ──
const autoGeneratedEntries: OptionPluginMapping[] = Object.entries(needsPluginMap).flatMap(
  ([packageName, entry]) =>
    entry.optionPaths.map((optionPath) => ({
      optionPath,
      packageName,
      description: describePackage(packageName),
    }))
);

// ── Manually curated entries (interactions, updaters, interactivity modes) ──
// These supplement the auto-generated map; packages already in needsPluginMap
// are excluded to keep the auto-generated paths as ground truth.
const manualEntries: OptionPluginMapping[] = [
  {
    optionPath: "particles.links",
    packageName: "@tsparticles/interaction-particles-links",
    description: "Connecting lines between particles",
  },
  {
    optionPath: "particles.collisions",
    packageName: "@tsparticles/interaction-particles-collisions",
    description: "Particle collision physics",
  },
  {
    optionPath: "particles.bounce",
    packageName: "@tsparticles/interaction-particles-collisions",
    description: "Particle bounce on collision",
  },
  {
    optionPath: "particles.move.attract",
    packageName: "@tsparticles/interaction-particles-attract",
    description: "Particle-to-particle attraction",
  },
  {
    optionPath: "particles.move.repulse",
    packageName: "@tsparticles/interaction-particles-repulse",
    description: "Particle-to-particle repulsion",
  },
  {
    optionPath: "particles.destroy",
    packageName: "@tsparticles/updater-destroy",
    description: "Particle destroy/split behavior",
  },
  {
    optionPath: "particles.gradient",
    packageName: "@tsparticles/updater-gradient",
    description: "Gradient color animation",
  },
  {
    optionPath: "particles.life",
    packageName: "@tsparticles/updater-life",
    description: "Particle lifetime control",
  },
  {
    optionPath: "particles.opacity.animation",
    packageName: "@tsparticles/updater-opacity",
    description: "Opacity animation",
  },
  {
    optionPath: "particles.orbit",
    packageName: "@tsparticles/updater-orbit",
    description: "Orbital motion",
  },
  {
    optionPath: "particles.move.outModes",
    packageName: "@tsparticles/updater-out-modes",
    description: "Out-of-bounds behavior",
  },
  {
    optionPath: "particles.roll",
    packageName: "@tsparticles/updater-roll",
    description: "Rolling rotation animation",
  },
  {
    optionPath: "particles.rotate",
    packageName: "@tsparticles/updater-rotate",
    description: "Rotation animation",
  },
  {
    optionPath: "particles.size.animation",
    packageName: "@tsparticles/updater-size",
    description: "Size animation",
  },
  {
    optionPath: "particles.tilt",
    packageName: "@tsparticles/updater-tilt",
    description: "3D tilt animation",
  },
  {
    optionPath: "particles.twinkle",
    packageName: "@tsparticles/updater-twinkle",
    description: "Twinkle/sparkle effect",
  },
  {
    optionPath: "particles.wobble",
    packageName: "@tsparticles/updater-wobble",
    description: "Wobble oscillation animation",
  },
  {
    optionPath: "interactivity.modes.attract",
    packageName: "@tsparticles/interaction-external-attract",
    description: "Attract particles to cursor",
  },
  {
    optionPath: "interactivity.modes.bounce",
    packageName: "@tsparticles/interaction-external-bounce",
    description: "Bounce particles from cursor",
  },
  {
    optionPath: "interactivity.modes.bubble",
    packageName: "@tsparticles/interaction-external-bubble",
    description: "Bubble particles near cursor",
  },
  {
    optionPath: "interactivity.modes.cannon",
    packageName: "@tsparticles/interaction-external-cannon",
    description: "Cannon fire particles on click",
  },
  {
    optionPath: "interactivity.modes.connect",
    packageName: "@tsparticles/interaction-external-connect",
    description: "Connect cursor to particles",
  },
  {
    optionPath: "interactivity.modes.destroy",
    packageName: "@tsparticles/interaction-external-destroy",
    description: "Destroy particles at cursor",
  },
  {
    optionPath: "interactivity.modes.drag",
    packageName: "@tsparticles/interaction-external-drag",
    description: "Drag particles with cursor",
  },
  {
    optionPath: "interactivity.modes.grab",
    packageName: "@tsparticles/interaction-external-grab",
    description: "Grab/connect cursor to particles",
  },
  {
    optionPath: "interactivity.events.onHover.parallax",
    packageName: "@tsparticles/interaction-external-parallax",
    description: "Parallax hover effect",
  },
  {
    optionPath: "interactivity.modes.particle",
    packageName: "@tsparticles/interaction-external-particle",
    description: "Spawn particles on click",
  },
  {
    optionPath: "interactivity.modes.pause",
    packageName: "@tsparticles/interaction-external-pause",
    description: "Pause animation on hover",
  },
  {
    optionPath: "interactivity.modes.pop",
    packageName: "@tsparticles/interaction-external-pop",
    description: "Pop particles on click",
  },
  {
    optionPath: "interactivity.modes.push",
    packageName: "@tsparticles/interaction-external-push",
    description: "Push new particles on click",
  },
  {
    optionPath: "interactivity.modes.remove",
    packageName: "@tsparticles/interaction-external-remove",
    description: "Remove particles on click",
  },
  {
    optionPath: "interactivity.modes.repulse",
    packageName: "@tsparticles/interaction-external-repulse",
    description: "Repulse particles from cursor",
  },
  {
    optionPath: "interactivity.modes.slow",
    packageName: "@tsparticles/interaction-external-slow",
    description: "Slow particles near cursor",
  },
  {
    optionPath: "interactivity.modes.trail",
    packageName: "@tsparticles/interaction-external-trail",
    description: "Mouse trail effect",
  },
  {
    optionPath: "interactivity.modes.light",
    packageName: "@tsparticles/interaction-light",
    description: "Light source interaction",
  },
];

// Auto-generated entries take priority; manual entries only add packages
// not covered by needsPluginMap (interactions, updaters, interactivity modes)
const additionalEntries = manualEntries.filter(
  (e) => !autoGeneratedPackages.has(e.packageName)
);

export const optionToPlugin: OptionPluginMapping[] = [
  ...autoGeneratedEntries,
  ...additionalEntries,
];
