Angular:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
Inferno:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
jQuery:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
Preact:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
React:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
Solid:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
Svelte:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
Vue 2:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
Vue 3:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
  
Wordpress:
  comment: |
    This repository is now only about tsParticles core library, if you need support for angular please open an issue in the [dedicated repository](https://github.com/tsparticles/angular)
  close: true
  lock: true
