project_id: 919303
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /websites/website/docs/index.md
    translation: /websites/website/docs/%two_letters_code%/index.md
  - source: /websites/website/docs/guide/**/*.md
    translation: /websites/website/docs/%two_letters_code%/guide/**/%original_file_name%
  - source: /websites/website/docs/guides/**/*.md
    translation: /websites/website/docs/%two_letters_code%/guides/**/%original_file_name%
  - source: /websites/website/docs/options/**/*.md
    translation: /websites/website/docs/%two_letters_code%/options/**/%original_file_name%
  - source: /websites/confetti/src/i18n/en.json
    translation: /websites/confetti/src/i18n/%two_letters_code%.json
  - source: /websites/ribbons/src/i18n/en.json
    translation: /websites/ribbons/src/i18n/%two_letters_code%.json
