packages:
  - bundles/*
  - demo/*
  - effects/*
  - engine
  - interactions/*
  - interactions/external/*
  - interactions/particles/*
  - move/*
  - paths/*
  - plugins/*
  - plugins/colors/*
  - plugins/easings/*
  - plugins/emittersShapes/*
  - plugins/exports/*
  - shapes/*
  - updaters/*
  - utils/*
  - websites/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - canvas
  - electron
  - esbuild
  - nx
