import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from "fs";
import { join, relative, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = join(__dirname, "..", "..", "..");

const scanDirs = ["plugins", "interactions", "shapes", "updaters", "effects", "paths", "colors", "easings", "emitter-shapes"];

interface Entry {
  optionPath: string;
  packageName: string;
  sourceFile: string;
}

const entries: Entry[] = [];

function extractBody(filePath: string): string | null {
  const content = readFileSync(filePath, "utf-8");

  const defRegex = /(?:^|\n)\s*needsPlugin\s*\(/m;
  const defMatch = content.match(defRegex);
  if (!defMatch) return null;

  const parenStart = defMatch.index! + defMatch[0].length;

  let i = parenStart;
  let parenDepth = 1;
  while (i < content.length && parenDepth > 0) {
    if (content[i] === "(") parenDepth++;
    else if (content[i] === ")") parenDepth--;
    i++;
  }

  while (i < content.length && content[i] !== "{") {
    if (content[i] === ";") return null;
    i++;
  }

  if (i >= content.length || content[i] !== "{") return null;

  const braceStart = i + 1;
  let depth = 1;
  let j = braceStart;
  while (j < content.length && depth > 0) {
    if (content[j] === "{") depth++;
    else if (content[j] === "}") depth--;
    j++;
  }

  return content.slice(braceStart, j - 1);
}

const skipWords = new Set([
  "options", "return", "false", "true", "null", "undefined", "this", "length",
  "if", "else", "const", "let", "var", "function", "isArray", "enable", "type",
  "import", "export", "default", "from", "particles", "interactivity",
]);

function extractOptionKey(filePath: string): string | null {
  const body = extractBody(filePath);
  if (!body) return null;

  // Pure "return true" with no conditions = always-on plugin
  const trimmedBody = body.trim();
  if (/^return\s+true\s*;?\s*$/.test(trimmedBody)) return null;

  // Collect all options?.X and options.X references
  const candidates = new Map<string, number>();
  const re = /options\s*\??\s*\.\s*(\w+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(body)) !== null) {
    const key = m[1];
    if (!skipWords.has(key)) {
      candidates.set(key, (candidates.get(key) || 0) + 1);
    }
  }

  // Pick the most frequent non-common key
  let bestKey = "";
  let bestCount = 0;
  for (const [key, count] of candidates) {
    if (count > bestCount) {
      bestCount = count;
      bestKey = key;
    }
  }

  return bestKey || null;
}

function getPackageName(dir: string): string | null {
  const pkgPath = join(dir, "package.json");
  if (!existsSync(pkgPath)) return null;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
    return pkg.name || null;
  } catch {
    return null;
  }
}

function findTsFiles(dir: string): string[] {
  const results: string[] = [];
  if (!existsSync(dir)) return results;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findTsFiles(full));
    } else if (entry.isFile() && entry.name.endsWith(".ts")) {
      results.push(full);
    }
  }
  return results;
}

function scanDirectory(categoryDir: string) {
  if (!existsSync(categoryDir)) return;
  for (const entry of readdirSync(categoryDir, { withFileTypes: true })) {
    const fullPath = join(categoryDir, entry.name);
    if (!entry.isDirectory()) continue;
    const srcDir = join(fullPath, "src");
    const hasPkg = existsSync(join(fullPath, "package.json"));

    if (hasPkg && existsSync(srcDir)) {
      // It's a package with src dir
      const pkgName = getPackageName(fullPath);
      if (!pkgName) continue;

      const srcFiles = findTsFiles(srcDir);
      for (const file of srcFiles) {
        const key = extractOptionKey(file);
        if (key) {
          entries.push({
            optionPath: key,
            packageName: pkgName,
            sourceFile: relative(repoRoot, file),
          });
        }
      }
    } else if (!hasPkg) {
      // No package.json → might be a category dir, recurse
      scanDirectory(fullPath);
    }
  }
}

for (const dir of scanDirs) {
  scanDirectory(join(repoRoot, dir));
}

entries.sort((a, b) => a.optionPath.localeCompare(b.optionPath));

const output = `// Auto-generated by scripts/extractNeedsPlugin.ts
// Generated on ${new Date().toISOString().split("T")[0]}
// Run: npx tsx scripts/extractNeedsPlugin.ts

export interface NeedsPluginEntry {
  optionKeys: string[];
  optionPaths: string[];
}

export const needsPluginMap: Record<string, NeedsPluginEntry> = {
${entries.map(e => {
  const paths = JSON.stringify([e.optionPath]);
  return `  "${e.packageName}": {
    optionKeys: [],
    optionPaths: ${paths},
  },`;
}).join("\n")}
};
`;

const outDir = join(__dirname, "..", "src", "registry");
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "needsPluginMap.ts"), output, "utf-8");

console.log(`\nExtracted ${entries.length} needsPlugin entries.`);
if (entries.length === 0) {
  console.log("No entries found! Check scanDirs paths.");
  process.exit(1);
}
for (const e of entries) {
  console.log(`  ${e.packageName.padEnd(45)} -> options?.${e.optionPath.padEnd(20)} (${e.sourceFile})`);
}
