import type { PackageInfo } from "../types.js";

export function getOptionsGuideResource(): string {
  const lines: string[] = [];

  lines.push("# tsParticles Options Guide");
  lines.push("");
  lines.push("Complete structural guide to tsParticles `ISourceOptions` configuration.");
  lines.push("Options are specified as a JSON object passed to `tsParticles.load()`.");
  lines.push("");

  lines.push("## Top-Level Options");
  lines.push("");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `autoPlay` | `boolean` | `true` | Automatically start animation |");
  lines.push("| `background` | `object` | — | Background color, opacity, image, position |");
  lines.push("| `background.color` | `string | IOptionsColor` | — | Background color value |");
  lines.push("| `background.opacity` | `number` | `1` | Background opacity |");
  lines.push("| `background.image` | `string` | — | CSS background image URL |");
  lines.push("| `background.position` | `string` | `50% 50%` | Background position |");
  lines.push("| `background.repeat` | `string` | `no-repeat` | Background repeat |");
  lines.push("| `background.size` | `string` | `cover` | Background size |");
  lines.push("| `clear` | `boolean` | `true` | Clear canvas before each frame |");
  lines.push("| `delay` | `number` | `0` | Delay before starting animation |");
  lines.push("| `detectRetina` | `boolean` | `true` | Automatically detect and use retina resolution |");
  lines.push("| `duration` | `number` | `0` | Animation duration in seconds (0 = infinite) |");
  lines.push("| `fpsLimit` | `number` | `120` | Maximum FPS |");
  lines.push("| `fullScreen` | `boolean | object` | `false` | Enable fullscreen canvas |");
  lines.push("| `fullScreen.enable` | `boolean` | — | Fill the entire viewport |");
  lines.push("| `fullScreen.zIndex` | `number` | `-1` | Z-index for fullscreen canvas |");
  lines.push("| `hdr` | `boolean` | `true` | High dynamic range rendering |");
  lines.push("| `key` | `string` | — | Unique key for this instance |");
  lines.push("| `name` | `string` | — | Name for this configuration |");
  lines.push("| `palette` | `string` | — | Color palette name to use |");
  lines.push("| `pauseOnBlur` | `boolean` | `true` | Pause when page loses focus |");
  lines.push("| `pauseOnOutsideViewport` | `boolean` | `true` | Pause when canvas is outside viewport |");
  lines.push("| `preset` | `string | string[]` | — | Preset name(s) to load |");
  lines.push("| `smooth` | `boolean` | `false` | Enable smooth rendering |");
  lines.push("| `style` | `object` | `{}` | CSS styles for the canvas element |");
  lines.push("| `zLayers` | `number` | `100` | Maximum number of z-layers |");
  lines.push("");

  lines.push("## Particles Options (`particles` property)");
  lines.push("");
  lines.push("### `particles.number` — Particle Count");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `number.value` | `number | { min, max }` | `80` | Number of particles |");
  lines.push("| `number.density.enable` | `boolean` | `false` | Adjust count based on canvas area |");
  lines.push("| `number.density.width` | `number` | — | Density calculation width |");
  lines.push("| `number.density.height` | `number` | — | Density calculation height |");
  lines.push("| `number.limit.mode` | `string` | `delete` | What happens when limit reached |");
  lines.push("| `number.limit.value` | `number` | `0` | Maximum particle limit (0 = no limit) |");
  lines.push("");

  lines.push("### `particles.color` — Particle Color");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `color.value` | `string | string[] | IAnimatableColor` | — | Particle color(s) |");
  lines.push("| `color.animation.enable` | `boolean` | `false` | Enable color animation |");
  lines.push("| `color.animation.speed` | `number` | `1` | Color animation speed |");
  lines.push("| `color.animation.sync` | `boolean` | `false` | Sync color animations |");
  lines.push("");

  lines.push("### `particles.shape` — Particle Shape");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `shape.type` | `string | string[]` | `circle` | Shape type(s): circle, square, star, heart, emoji, image, text, polygon, etc. |");
  lines.push("| `shape.options` | `object` | `{}` | Shape-specific options (per shape type) |");
  lines.push("| `shape.options.image.src` | `string` | — | Image URL (for 'image' shape) |");
  lines.push("| `shape.options.image.width` | `number` | — | Image width (for 'image' shape) |");
  lines.push("| `shape.options.image.height` | `number` | — | Image height (for 'image' shape) |");
  lines.push("| `shape.options.text.value` | `string` | — | Text to render (for 'text' shape) |");
  lines.push("| `shape.options.polygon.sides` | `number` | `5` | Polygon sides (for 'polygon' shape) |");
  lines.push("| `shape.options.emoji.value` | `string` | — | Emoji character (for 'emoji' shape) |");
  lines.push("| `shape.options.star.sides` | `number` | `5` | Star points (for 'star' shape) |");
  lines.push("");

  lines.push("### `particles.opacity` — Opacity");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `opacity.value` | `number | { min, max }` | `1` | Particle opacity |");
  lines.push("| `opacity.animation.enable` | `boolean` | `false` | Enable opacity animation |");
  lines.push("| `opacity.animation.speed` | `number` | `2` | Opacity change speed per second |");
  lines.push("| `opacity.animation.minimumValue` | `number` | — | Minimum opacity during animation |");
  lines.push("| `opacity.animation.startValue` | `string` | `random` | Start value (random, min, max) |");
  lines.push("| `opacity.animation.sync` | `boolean` | `false` | Sync opacity animations |");
  lines.push("");

  lines.push("### `particles.size` — Size");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `size.value` | `number | { min, max }` | `3` | Particle size |");
  lines.push("| `size.animation.enable` | `boolean` | `false` | Enable size animation |");
  lines.push("| `size.animation.speed` | `number` | `2` | Size change speed per second |");
  lines.push("| `size.animation.minimumValue` | `number` | — | Minimum size during animation |");
  lines.push("| `size.animation.startValue` | `string` | `random` | Start value (random, min, max) |");
  lines.push("| `size.animation.sync` | `boolean` | `false` | Sync size animations |");
  lines.push("");

  lines.push("### `particles.links` — Particle Links (requires @tsparticles/interaction-particles-links)");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `links.enable` | `boolean` | `false` | Draw connecting lines between particles |");
  lines.push("| `links.distance` | `number` | `100` | Maximum link distance |");
  lines.push("| `links.color` | `string | IOptionsColor` | — | Link line color |");
  lines.push("| `links.opacity` | `number` | `0.4` | Link line opacity |");
  lines.push("| `links.width` | `number` | `1` | Link line width |");
  lines.push("| `links.triangles.enable` | `boolean` | `false` | Connect links into triangles |");
  lines.push("| `links.triangles.opacity` | `number` | `0.1` | Triangle fill opacity |");
  lines.push("");

  lines.push("### `particles.move` — Movement");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `move.enable` | `boolean` | `true` | Enable particle movement |");
  lines.push("| `move.speed` | `number | { min, max }` | `2` | Movement speed |");
  lines.push("| `move.direction` | `string` | `none` | Direction: none, top, top-right, right, bottom-right, bottom, bottom-left, left, top-left |");
  lines.push("| `move.random` | `boolean` | `false` | Random direction |");
  lines.push("| `move.straight` | `boolean` | `false` | Move in straight line |");
  lines.push("| `move.outModes.default` | `string` | `out` | Out-of-bounds mode: bounce, destroy, none, out |");
  lines.push("| `move.outModes.top/bottom/left/right` | `string` | — | Per-side out-of-bounds mode |");
  lines.push("| `move.bounce` | `boolean` | `false` | Bounce off canvas edges |");
  lines.push("| `move.attract.enable` | `boolean` | `false` | Attract particles to center |");
  lines.push("| `move.attract.rotate.x/y` | `number` | — | Attraction rotation |");
  lines.push("| `move.gravity.enable` | `boolean` | `false` | Enable gravity |");
  lines.push("| `move.gravity.acceleration` | `number` | `9.81` | Gravity acceleration |");
  lines.push("| `move.path.enable` | `boolean` | `false` | Follow a path generator |");
  lines.push("| `move.path.generator` | `string` | — | Path generator type |");
  lines.push("| `move.path.options` | `object` | — | Path generator options |");
  lines.push("| `move.spin.enable` | `boolean` | `false` | Spin movement |");
  lines.push("| `move.spin.speed` | `number` | — | Spin speed |");
  lines.push("");

  lines.push("### `particles.collisions` — Collision (requires @tsparticles/interaction-particles-collisions)");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `collisions.enable` | `boolean` | `false` | Particles collide with each other |");
  lines.push("| `collisions.mode` | `string` | `bounce` | Collision mode: bounce, absorb |");
  lines.push("");

  lines.push("### `particles.life` — Lifetime (requires @tsparticles/updater-life)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `life.count` | `number` | Number of times a particle can respawn (0 = infinite) |");
  lines.push("| `life.delay` | `number | { min, max }` | Delay before a particle starts its life |");
  lines.push("| `life.duration` | `number | { min, max }` | Particle lifetime duration |");
  lines.push("");

  lines.push("### `particles.rotate` — Rotation (requires @tsparticles/updater-rotate)");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `rotate.value` | `number | { min, max }` | `0` | Rotation angle |");
  lines.push("| `rotate.animation.enable` | `boolean` | `false` | Enable rotation animation |");
  lines.push("| `rotate.animation.speed` | `number` | `5` | Rotation speed per second |");
  lines.push("| `rotate.animation.sync` | `boolean` | `false` | Sync rotations |");
  lines.push("| `rotate.direction` | `string` | `clockwise` | Direction: clockwise, counter-clockwise, random |");
  lines.push("");

  lines.push("### `particles.tilt` — Tilt (requires @tsparticles/updater-tilt)");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `tilt.value` | `number | { min, max }` | `0` | Tilt angle |");
  lines.push("| `tilt.animation.enable` | `boolean` | `false` | Enable tilt animation |");
  lines.push("| `tilt.animation.speed` | `number` | `5` | Tilt animation speed |");
  lines.push("| `tilt.direction` | `string` | `clockwise` | Tilt direction |");
  lines.push("");

  lines.push("### `particles.wobble` — Wobble (requires @tsparticles/updater-wobble)");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `wobble.distance` | `number` | `5` | Wobble oscillation distance |");
  lines.push("| `wobble.enable` | `boolean` | `false` | Enable wobble |");
  lines.push("| `wobble.speed` | `number` | — | Wobble oscillation speed |");
  lines.push("");

  lines.push("### `particles.roll` — Roll (requires @tsparticles/updater-roll)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `roll.enable` | `boolean` | Enable rolling effect |");
  lines.push("| `roll.mode` | `string` | Roll mode: horizontal, vertical, both |");
  lines.push("| `roll.speed` | `number` | Roll rotation speed |");
  lines.push("");

  lines.push("### `particles.twinkle` — Twinkle (requires @tsparticles/updater-twinkle)");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `twinkle.lines.enable` | `boolean` | `false` | Enable line twinkle |");
  lines.push("| `twinkle.lines.frequency` | `number` | `0.05` | Line twinkle frequency |");
  lines.push("| `twinkle.lines.opacity` | `number` | `0.5` | Line twinkle opacity |");
  lines.push("| `twinkle.particles.enable` | `boolean` | `false` | Enable particle twinkle |");
  lines.push("| `twinkle.particles.frequency` | `number` | `0.05` | Particle twinkle frequency |");
  lines.push("| `twinkle.particles.opacity` | `number` | `0.5` | Particle twinkle opacity |");
  lines.push("");

  lines.push("### `particles.destroy` — Destroy (requires @tsparticles/updater-destroy)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `destroy.mode` | `string` | Destroy mode: split, explode |");
  lines.push("| `destroy.split.count` | `number` | Number of split pieces |");
  lines.push("| `destroy.split.factor` | `object` | Size/orbit factor for splits |");
  lines.push("| `destroy.split.rate` | `object` | Split rate configuration |");
  lines.push("");

  lines.push("### `particles.bounce` — Bounce");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `bounce.horizontal.value` | `number` | Horizontal bounce factor |");
  lines.push("| `bounce.vertical.value` | `number` | Vertical bounce factor |");
  lines.push("");

  lines.push("### `particles.groups` — Particle Groups");
  lines.push("Groups allow different particle configurations within the same container.");
  lines.push("Each group key maps to a partial IParticlesOptions object.");
  lines.push("```json");
  lines.push('"groups": {');
  lines.push('  "red": { "color": { "value": "#ff0000" }, "size": { "value": 5 } },');
  lines.push('  "blue": { "color": { "value": "#0000ff" }, "size": { "value": 3 } }');
  lines.push("}");
  lines.push("```");
  lines.push("");

  lines.push("### `particles.reduceDuplicates`");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `reduceDuplicates` | `boolean` | `false` | Reduce duplicate particles |");
  lines.push("");

  lines.push("### `particles.zIndex` — Z-Index / Depth");
  lines.push("| Option | Type | Default | Description |");
  lines.push("|--------|------|---------|-------------|");
  lines.push("| `zIndex.value` | `number | { min, max }` | `0` | Z-index value |");
  lines.push("| `zIndex.velocityRate` | `number` | `1` | Velocity effect on z-index |");
  lines.push("| `zIndex.sizeRate` | `number` | `1` | Size effect on z-index |");
  lines.push("| `zIndex.opacityRate` | `number` | `1` | Opacity effect on z-index |");
  lines.push("");

  lines.push("## Interactivity Options");
  lines.push("");
  lines.push("### `interactivity.events` — Event Triggers (requires @tsparticles/plugin-interactivity)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `events.onHover.enable` | `boolean` | Enable hover interactions |");
  lines.push("| `events.onHover.mode` | `string | string[]` | Hover mode(s) to activate |");
  lines.push("| `events.onHover.parallax.enable` | `boolean` | Enable parallax effect |");
  lines.push("| `events.onHover.parallax.force` | `number` | Parallax force |");
  lines.push("| `events.onHover.parallax.smooth` | `number` | Parallax smoothing |");
  lines.push("| `events.onClick.enable` | `boolean` | Enable click interactions |");
  lines.push("| `events.onClick.mode` | `string | string[]` | Click mode(s) to activate |");
  lines.push("| `events.resize` | `boolean` \`true\` | Enable resize events |");
  lines.push("");

  lines.push("### Hover/Click Modes");
  lines.push("");
  lines.push("Available interaction modes and their packages:");
  lines.push("| Mode | Package | Description |");
  lines.push("|------|---------|-------------|");
  lines.push("| `attract` | `@tsparticles/interaction-external-attract` | Attract particles to cursor |");
  lines.push("| `bounce` | `@tsparticles/interaction-external-bounce` | Bounce particles from cursor |");
  lines.push("| `bubble` | `@tsparticles/interaction-external-bubble` | Enlarge particles near cursor |");
  lines.push("| `connect` | `@tsparticles/interaction-external-connect` | Connect cursor to particles |");
  lines.push("| `destroy` | `@tsparticles/interaction-external-destroy` | Destroy particles at cursor |");
  lines.push("| `grab` | `@tsparticles/interaction-external-grab` | Grab/connect lines to particles |");
  lines.push("| `pause` | `@tsparticles/interaction-external-pause` | Pause animation on hover |");
  lines.push("| `push` | `@tsparticles/interaction-external-push` | Add particles on click |");
  lines.push("| `remove` | `@tsparticles/interaction-external-remove` | Remove particles on click |");
  lines.push("| `repulse` | `@tsparticles/interaction-external-repulse` | Repulse from cursor |");
  lines.push("| `slow` | `@tsparticles/interaction-external-slow` | Slow particles near cursor |");
  lines.push("| `trail` | `@tsparticles/interaction-external-trail` | Mouse trail effect |");
  lines.push("| `cannon` | `@tsparticles/interaction-external-cannon` | Fire particles on click |");
  lines.push("| `particle` | `@tsparticles/interaction-external-particle` | Spawn particle on click |");
  lines.push("| `pop` | `@tsparticles/interaction-external-pop` | Pop particles on click |");
  lines.push("| `light` | `@tsparticles/interaction-light` | Light source effect |");
  lines.push("| `drag` | `@tsparticles/interaction-external-drag` | Drag particles |");
  lines.push("");

  lines.push("## Plugin-Specific Options");
  lines.push("");

  lines.push("### Absorbers (`@tsparticles/plugin-absorbers`)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `absorbers` | `object | object[]` | Absorber configuration(s) |");
  lines.push("| `absorbers[].position` | `{ x, y }` | Absorber position |");
  lines.push("| `absorbers[].size` | `{ value, limit }` | Absorber size |");
  lines.push("| `absorbers[].color` | `string | IOptionsColor` | Absorber color |");
  lines.push("| `absorbers[].opacity` | `number` | Absorber opacity |");
  lines.push("| `absorbers[].draggable` | `boolean` | Make absorber draggable |");
  lines.push("| `absorbers[].orbit` | `boolean` | Particles orbit before being absorbed |");
  lines.push("| `absorbers[].destroy` | `boolean` | Destroy absorbed particles |");
  lines.push("");

  lines.push("### Emitters (`@tsparticles/plugin-emitters`)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `emitters` | `object | object[]` | Emitter configuration(s) |");
  lines.push("| `emitters[].position` | `{ x, y }` | Emitter position |");
  lines.push("| `emitters[].size` | `{ width, height }` | Emitter area size |");
  lines.push("| `emitters[].rate` | `{ quantity, delay }` | Particle emission rate |");
  lines.push("| `emitters[].life.count` | `number` | Emitter lifetime (0 = infinite) |");
  lines.push("| `emitters[].life.delay` | `number` | Delay before emitting starts |");
  lines.push("| `emitters[].life.duration` | `number` | How long emitter stays active |");
  lines.push("| `emitters[].particles` | `IParticlesOptions` | Overrides for emitted particles |");
  lines.push("| `emitters[].shape.type` | `string` | Emission shape: circle, square, path, canvas, polygon |");
  lines.push("");

  lines.push("### Background Mask (`@tsparticles/plugin-background-mask`)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `backgroundMask.enable` | `boolean` | Enable background masking |");
  lines.push("| `backgroundMask.cover.color` | `string | IOptionsColor` | Cover color |");
  lines.push("| `backgroundMask.cover.opacity` | `number` | Cover opacity |");
  lines.push("");

  lines.push("### Polygon Mask (`@tsparticles/plugin-polygon-mask`)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `polygon.enable` | `boolean` | Enable polygon mask |");
  lines.push("| `polygon.type` | `string` | Polygon type: inline, outside, inside, none |");
  lines.push("| `polygon.url` | `string` | SVG URL for the polygon |");
  lines.push("| `polygon.data` | `string` | Inline SVG path data |");
  lines.push("| `polygon.scale` | `number` | Polygon scale |");
  lines.push("| `polygon.position` | `{ x, y }` | Polygon position |");
  lines.push("");

  lines.push("### Sounds (`@tsparticles/plugin-sounds`)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `sounds.enable` | `boolean` | Enable sound effects |");
  lines.push("");

  lines.push("### Themes (`@tsparticles/plugin-themes`)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `themes` | `object[]` | Theme definitions |");
  lines.push("| `themes[].name` | `string` | Theme name |");
  lines.push("| `themes[].default` | `object` | Dark/light default |");
  lines.push("| `themes[].options` | `ISourceOptions` | Theme-specific options |");
  lines.push("");

  lines.push("### Responsive (`@tsparticles/plugin-responsive`)");
  lines.push("| Option | Type | Description |");
  lines.push("|--------|------|-------------|");
  lines.push("| `responsive` | `object[]` | Responsive breakpoint configs |");
  lines.push("| `responsive[].maxWidth` | `number` | Max width for this breakpoint |");
  lines.push("| `responsive[].mode` | `string` | Screen mode |");
  lines.push("| `responsive[].options` | `ISourceOptions` | Options for this breakpoint |");
  lines.push("");

  lines.push("## Common Configuration Examples");
  lines.push("");
  lines.push("### Minimal Setup");
  lines.push("```json");
  lines.push('{ "particles": { "number": { "value": 50 }, "shape": { "type": "circle" }, "move": { "speed": 2 } } }');
  lines.push("```");
  lines.push("");
  lines.push("### Starry Night");
  lines.push("```json");
  lines.push('{');
  lines.push('  "background": { "color": "#000" },');
  lines.push('  "particles": {');
  lines.push('    "number": { "value": 100 },');
  lines.push('    "color": { "value": "#fff" },');
  lines.push('    "shape": { "type": "circle" },');
  lines.push('    "opacity": { "value": { "min": 0.1, "max": 1 } },');
  lines.push('    "size": { "value": { "min": 1, "max": 3 } },');
  lines.push('    "move": { "enable": false }');
  lines.push('  }');
  lines.push("}");
  lines.push("```");
  lines.push("");
  lines.push("### Connected Particles (Network)");
  lines.push("```json");
  lines.push('{');
  lines.push('  "background": { "color": "#0d1117" },');
  lines.push('  "particles": {');
  lines.push('    "number": { "value": 80 },');
  lines.push('    "color": { "value": "#58a6ff" },');
  lines.push('    "links": { "enable": true, "distance": 150, "color": "#8b949e", "opacity": 0.4 },');
  lines.push('    "move": { "speed": 1 }');
  lines.push('  }');
  lines.push("}");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}
