/**
 * @returns the options guide resource
 */
export function getOptionsGuideResource(): string {
  return [
    "# tsParticles Options Guide",
    "",
    "Complete structural guide to tsParticles `ISourceOptions` configuration.",
    "Options are specified as a JSON object passed to `tsParticles.load()`.",
    "",
    "## Top-Level Options",
    "",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `autoPlay` | `boolean` | `true` | Automatically start animation |",
    "| `background` | `object` | — | Background color, opacity, image, position |",
    "| `background.color` | `string | IOptionsColor` | — | Background color value |",
    "| `background.opacity` | `number` | `1` | Background opacity |",
    "| `background.image` | `string` | — | CSS background image URL |",
    "| `background.position` | `string` | `50% 50%` | Background position |",
    "| `background.repeat` | `string` | `no-repeat` | Background repeat |",
    "| `background.size` | `string` | `cover` | Background size |",
    "| `clear` | `boolean` | `true` | Clear canvas before each frame |",
    "| `delay` | `number` | `0` | Delay before starting animation |",
    "| `detectRetina` | `boolean` | `true` | Automatically detect and use retina resolution |",
    "| `duration` | `number` | `0` | Animation duration in seconds (0 = infinite) |",
    "| `fpsLimit` | `number` | `120` | Maximum FPS |",
    "| `fullScreen` | `boolean | object` | `false` | Enable fullscreen canvas |",
    "| `fullScreen.enable` | `boolean` | — | Fill the entire viewport |",
    "| `fullScreen.zIndex` | `number` | `-1` | Z-index for fullscreen canvas |",
    "| `hdr` | `boolean` | `true` | High dynamic range rendering |",
    "| `key` | `string` | — | Unique key for this instance |",
    "| `name` | `string` | — | Name for this configuration |",
    "| `palette` | `string` | — | Color palette name to use |",
    "| `pauseOnBlur` | `boolean` | `true` | Pause when page loses focus |",
    "| `pauseOnOutsideViewport` | `boolean` | `true` | Pause when canvas is outside viewport |",
    "| `preset` | `string | string[]` | — | Preset name(s) to load |",
    "| `smooth` | `boolean` | `false` | Enable smooth rendering |",
    "| `style` | `object` | `{}` | CSS styles for the canvas element |",
    "| `zLayers` | `number` | `100` | Maximum number of z-layers |",
    "",
    "## Particles Options (`particles` property)",
    "",
    "### `particles.number` — Particle Count",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `number.value` | `number | { min, max }` | `80` | Number of particles |",
    "| `number.density.enable` | `boolean` | `false` | Adjust count based on canvas area |",
    "| `number.density.width` | `number` | — | Density calculation width |",
    "| `number.density.height` | `number` | — | Density calculation height |",
    "| `number.limit.mode` | `string` | `delete` | What happens when limit reached |",
    "| `number.limit.value` | `number` | `0` | Maximum particle limit (0 = no limit) |",
    "",
    "### `particles.color` — Particle Color",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `color.value` | `string | string[] | IAnimatableColor` | — | Particle color(s) |",
    "| `color.animation.enable` | `boolean` | `false` | Enable color animation |",
    "| `color.animation.speed` | `number` | `1` | Color animation speed |",
    "| `color.animation.sync` | `boolean` | `false` | Sync color animations |",
    "",
    "### `particles.shape` — Particle Shape",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `shape.type` | `string | string[]` | `circle` | Shape type(s): circle, square, star, heart, emoji, image, text, polygon, etc. |",
    "| `shape.options` | `object` | `{}` | Shape-specific options (per shape type) |",
    "| `shape.options.image.src` | `string` | — | Image URL (for 'image' shape) |",
    "| `shape.options.image.width` | `number` | — | Image width (for 'image' shape) |",
    "| `shape.options.image.height` | `number` | — | Image height (for 'image' shape) |",
    "| `shape.options.text.value` | `string` | — | Text to render (for 'text' shape) |",
    "| `shape.options.polygon.sides` | `number` | `5` | Polygon sides (for 'polygon' shape) |",
    "| `shape.options.emoji.value` | `string` | — | Emoji character (for 'emoji' shape) |",
    "| `shape.options.star.sides` | `number` | `5` | Star points (for 'star' shape) |",
    "",
    "### `particles.opacity` — Opacity",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `opacity.value` | `number | { min, max }` | `1` | Particle opacity |",
    "| `opacity.animation.enable` | `boolean` | `false` | Enable opacity animation |",
    "| `opacity.animation.speed` | `number` | `2` | Opacity change speed per second |",
    "| `opacity.animation.minimumValue` | `number` | — | Minimum opacity during animation |",
    "| `opacity.animation.startValue` | `string` | `random` | Start value (random, min, max) |",
    "| `opacity.animation.sync` | `boolean` | `false` | Sync opacity animations |",
    "",
    "### `particles.size` — Size",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `size.value` | `number | { min, max }` | `3` | Particle size |",
    "| `size.animation.enable` | `boolean` | `false` | Enable size animation |",
    "| `size.animation.speed` | `number` | `2` | Size change speed per second |",
    "| `size.animation.minimumValue` | `number` | — | Minimum size during animation |",
    "| `size.animation.startValue` | `string` | `random` | Start value (random, min, max) |",
    "| `size.animation.sync` | `boolean` | `false` | Sync size animations |",
    "",
    "### `particles.links` — Particle Links (requires @tsparticles/interaction-particles-links)",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `links.enable` | `boolean` | `false` | Draw connecting lines between particles |",
    "| `links.distance` | `number` | `100` | Maximum link distance |",
    "| `links.color` | `string | IOptionsColor` | — | Link line color |",
    "| `links.opacity` | `number` | `0.4` | Link line opacity |",
    "| `links.width` | `number` | `1` | Link line width |",
    "| `links.triangles.enable` | `boolean` | `false` | Connect links into triangles |",
    "| `links.triangles.opacity` | `number` | `0.1` | Triangle fill opacity |",
    "",
    "### `particles.move` — Movement",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `move.enable` | `boolean` | `true` | Enable particle movement |",
    "| `move.speed` | `number | { min, max }` | `2` | Movement speed |",
    "| `move.direction` | `string` | `none` | Direction: none, top, top-right, right, bottom-right, bottom, bottom-left, left, top-left |",
    "| `move.random` | `boolean` | `false` | Random direction |",
    "| `move.straight` | `boolean` | `false` | Move in straight line |",
    "| `move.outModes.default` | `string` | `out` | Out-of-bounds mode: bounce, destroy, none, out |",
    "| `move.outModes.top/bottom/left/right` | `string` | — | Per-side out-of-bounds mode |",
    "| `move.bounce` | `boolean` | `false` | Bounce off canvas edges |",
    "| `move.attract.enable` | `boolean` | `false` | Attract particles to center |",
    "| `move.attract.rotate.x/y` | `number` | — | Attraction rotation |",
    "| `move.gravity.enable` | `boolean` | `false` | Enable gravity |",
    "| `move.gravity.acceleration` | `number` | `9.81` | Gravity acceleration |",
    "| `move.path.enable` | `boolean` | `false` | Follow a path generator |",
    "| `move.path.generator` | `string` | — | Path generator type |",
    "| `move.path.options` | `object` | — | Path generator options |",
    "| `move.spin.enable` | `boolean` | `false` | Spin movement |",
    "| `move.spin.speed` | `number` | — | Spin speed |",
    "",
    "### `particles.collisions` — Collision (requires @tsparticles/interaction-particles-collisions)",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `collisions.enable` | `boolean` | `false` | Particles collide with each other |",
    "| `collisions.mode` | `string` | `bounce` | Collision mode: bounce, absorb |",
    "",
    "### `particles.life` — Lifetime (requires @tsparticles/updater-life)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `life.count` | `number` | Number of times a particle can respawn (0 = infinite) |",
    "| `life.delay` | `number | { min, max }` | Delay before a particle starts its life |",
    "| `life.duration` | `number | { min, max }` | Particle lifetime duration |",
    "",
    "### `particles.rotate` — Rotation (requires @tsparticles/updater-rotate)",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `rotate.value` | `number | { min, max }` | `0` | Rotation angle |",
    "| `rotate.animation.enable` | `boolean` | `false` | Enable rotation animation |",
    "| `rotate.animation.speed` | `number` | `5` | Rotation speed per second |",
    "| `rotate.animation.sync` | `boolean` | `false` | Sync rotations |",
    "| `rotate.direction` | `string` | `clockwise` | Direction: clockwise, counter-clockwise, random |",
    "",
    "### `particles.tilt` — Tilt (requires @tsparticles/updater-tilt)",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `tilt.value` | `number | { min, max }` | `0` | Tilt angle |",
    "| `tilt.animation.enable` | `boolean` | `false` | Enable tilt animation |",
    "| `tilt.animation.speed` | `number` | `5` | Tilt animation speed |",
    "| `tilt.direction` | `string` | `clockwise` | Tilt direction |",
    "",
    "### `particles.wobble` — Wobble (requires @tsparticles/updater-wobble)",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `wobble.distance` | `number` | `5` | Wobble oscillation distance |",
    "| `wobble.enable` | `boolean` | `false` | Enable wobble |",
    "| `wobble.speed` | `number` | — | Wobble oscillation speed |",
    "",
    "### `particles.roll` — Roll (requires @tsparticles/updater-roll)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `roll.enable` | `boolean` | Enable rolling effect |",
    "| `roll.mode` | `string` | Roll mode: horizontal, vertical, both |",
    "| `roll.speed` | `number` | Roll rotation speed |",
    "",
    "### `particles.twinkle` — Twinkle (requires @tsparticles/updater-twinkle)",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `twinkle.lines.enable` | `boolean` | `false` | Enable line twinkle |",
    "| `twinkle.lines.frequency` | `number` | `0.05` | Line twinkle frequency |",
    "| `twinkle.lines.opacity` | `number` | `0.5` | Line twinkle opacity |",
    "| `twinkle.particles.enable` | `boolean` | `false` | Enable particle twinkle |",
    "| `twinkle.particles.frequency` | `number` | `0.05` | Particle twinkle frequency |",
    "| `twinkle.particles.opacity` | `number` | `0.5` | Particle twinkle opacity |",
    "",
    "### `particles.destroy` — Destroy (requires @tsparticles/updater-destroy)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `destroy.mode` | `string` | Destroy mode: split, explode |",
    "| `destroy.split.count` | `number` | Number of split pieces |",
    "| `destroy.split.factor` | `object` | Size/orbit factor for splits |",
    "| `destroy.split.rate` | `object` | Split rate configuration |",
    "",
    "### `particles.bounce` — Bounce",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `bounce.horizontal.value` | `number` | Horizontal bounce factor |",
    "| `bounce.vertical.value` | `number` | Vertical bounce factor |",
    "",
    "### `particles.groups` — Particle Groups",
    "Groups allow different particle configurations within the same container.",
    "Each group key maps to a partial IParticlesOptions object.",
    "```json",
    '"groups": {',
    '  "red": { "color": { "value": "#ff0000" }, "size": { "value": 5 } },',
    '  "blue": { "color": { "value": "#0000ff" }, "size": { "value": 3 } }',
    "}",
    "```",
    "",
    "### `particles.reduceDuplicates`",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `reduceDuplicates` | `boolean` | `false` | Reduce duplicate particles |",
    "",
    "### `particles.zIndex` — Z-Index / Depth",
    "| Option | Type | Default | Description |",
    "|--------|------|---------|-------------|",
    "| `zIndex.value` | `number | { min, max }` | `0` | Z-index value |",
    "| `zIndex.velocityRate` | `number` | `1` | Velocity effect on z-index |",
    "| `zIndex.sizeRate` | `number` | `1` | Size effect on z-index |",
    "| `zIndex.opacityRate` | `number` | `1` | Opacity effect on z-index |",
    "",
    "## Interactivity Options",
    "",
    "### `interactivity.events` — Event Triggers (requires @tsparticles/plugin-interactivity)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `events.onHover.enable` | `boolean` | Enable hover interactions |",
    "| `events.onHover.mode` | `string | string[]` | Hover mode(s) to activate |",
    "| `events.onHover.parallax.enable` | `boolean` | Enable parallax effect |",
    "| `events.onHover.parallax.force` | `number` | Parallax force |",
    "| `events.onHover.parallax.smooth` | `number` | Parallax smoothing |",
    "| `events.onClick.enable` | `boolean` | Enable click interactions |",
    "| `events.onClick.mode` | `string | string[]` | Click mode(s) to activate |",
    "| `events.resize` | `boolean` `true` | Enable resize events |",
    "",
    "### Hover/Click Modes",
    "",
    "Available interaction modes and their packages:",
    "| Mode | Package | Description |",
    "|------|---------|-------------|",
    "| `attract` | `@tsparticles/interaction-external-attract` | Attract particles to cursor |",
    "| `bounce` | `@tsparticles/interaction-external-bounce` | Bounce particles from cursor |",
    "| `bubble` | `@tsparticles/interaction-external-bubble` | Enlarge particles near cursor |",
    "| `connect` | `@tsparticles/interaction-external-connect` | Connect cursor to particles |",
    "| `destroy` | `@tsparticles/interaction-external-destroy` | Destroy particles at cursor |",
    "| `grab` | `@tsparticles/interaction-external-grab` | Grab/connect lines to particles |",
    "| `pause` | `@tsparticles/interaction-external-pause` | Pause animation on hover |",
    "| `push` | `@tsparticles/interaction-external-push` | Add particles on click |",
    "| `remove` | `@tsparticles/interaction-external-remove` | Remove particles on click |",
    "| `repulse` | `@tsparticles/interaction-external-repulse` | Repulse from cursor |",
    "| `slow` | `@tsparticles/interaction-external-slow` | Slow particles near cursor |",
    "| `trail` | `@tsparticles/interaction-external-trail` | Mouse trail effect |",
    "| `cannon` | `@tsparticles/interaction-external-cannon` | Fire particles on click |",
    "| `particle` | `@tsparticles/interaction-external-particle` | Spawn particle on click |",
    "| `pop` | `@tsparticles/interaction-external-pop` | Pop particles on click |",
    "| `light` | `@tsparticles/interaction-light` | Light source effect |",
    "| `drag` | `@tsparticles/interaction-external-drag` | Drag particles |",
    "",
    "## Plugin-Specific Options",
    "",
    "### Absorbers (`@tsparticles/plugin-absorbers`)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `absorbers` | `object | object[]` | Absorber configuration(s) |",
    "| `absorbers[].position` | `{ x, y }` | Absorber position |",
    "| `absorbers[].size` | `{ value, limit }` | Absorber size |",
    "| `absorbers[].color` | `string | IOptionsColor` | Absorber color |",
    "| `absorbers[].opacity` | `number` | Absorber opacity |",
    "| `absorbers[].draggable` | `boolean` | Make absorber draggable |",
    "| `absorbers[].orbit` | `boolean` | Particles orbit before being absorbed |",
    "| `absorbers[].destroy` | `boolean` | Destroy absorbed particles |",
    "",
    "### Emitters (`@tsparticles/plugin-emitters`)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `emitters` | `object | object[]` | Emitter configuration(s) |",
    "| `emitters[].position` | `{ x, y }` | Emitter position |",
    "| `emitters[].size` | `{ width, height }` | Emitter area size |",
    "| `emitters[].rate` | `{ quantity, delay }` | Particle emission rate |",
    "| `emitters[].life.count` | `number` | Emitter lifetime (0 = infinite) |",
    "| `emitters[].life.delay` | `number` | Delay before emitting starts |",
    "| `emitters[].life.duration` | `number` | How long emitter stays active |",
    "| `emitters[].particles` | `IParticlesOptions` | Overrides for emitted particles |",
    "| `emitters[].shape.type` | `string` | Emission shape: circle, square, path, canvas, polygon |",
    "",
    "### Background Mask (`@tsparticles/plugin-background-mask`)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `backgroundMask.enable` | `boolean` | Enable background masking |",
    "| `backgroundMask.cover.color` | `string | IOptionsColor` | Cover color |",
    "| `backgroundMask.cover.opacity` | `number` | Cover opacity |",
    "",
    "### Polygon Mask (`@tsparticles/plugin-polygon-mask`)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `polygon.enable` | `boolean` | Enable polygon mask |",
    "| `polygon.type` | `string` | Polygon type: inline, outside, inside, none |",
    "| `polygon.url` | `string` | SVG URL for the polygon |",
    "| `polygon.data` | `string` | Inline SVG path data |",
    "| `polygon.scale` | `number` | Polygon scale |",
    "| `polygon.position` | `{ x, y }` | Polygon position |",
    "",
    "### Sounds (`@tsparticles/plugin-sounds`)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `sounds.enable` | `boolean` | Enable sound effects |",
    "",
    "### Themes (`@tsparticles/plugin-themes`)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `themes` | `object[]` | Theme definitions |",
    "| `themes[].name` | `string` | Theme name |",
    "| `themes[].default` | `object` | Dark/light default |",
    "| `themes[].options` | `ISourceOptions` | Theme-specific options |",
    "",
    "### Responsive (`@tsparticles/plugin-responsive`)",
    "| Option | Type | Description |",
    "|--------|------|-------------|",
    "| `responsive` | `object[]` | Responsive breakpoint configs |",
    "| `responsive[].maxWidth` | `number` | Max width for this breakpoint |",
    "| `responsive[].mode` | `string` | Screen mode |",
    "| `responsive[].options` | `ISourceOptions` | Options for this breakpoint |",
    "",
    "## Common Configuration Examples",
    "",
    "### Minimal Setup",
    "```json",
    '{ "particles": { "number": { "value": 50 }, "shape": { "type": "circle" }, "move": { "speed": 2 } } }',
    "```",
    "",
    "### Starry Night",
    "```json",
    "{",
    '  "background": { "color": "#000" },',
    '  "particles": {',
    '    "number": { "value": 100 },',
    '    "color": { "value": "#fff" },',
    '    "shape": { "type": "circle" },',
    '    "opacity": { "value": { "min": 0.1, "max": 1 } },',
    '    "size": { "value": { "min": 1, "max": 3 } },',
    '    "move": { "enable": false }',
    "  }",
    "}",
    "```",
    "",
    "### Connected Particles (Network)",
    "```json",
    "{",
    '  "background": { "color": "#0d1117" },',
    '  "particles": {',
    '    "number": { "value": 80 },',
    '    "color": { "value": "#58a6ff" },',
    '    "links": { "enable": true, "distance": 150, "color": "#8b949e", "opacity": 0.4 },',
    '    "move": { "speed": 1 }',
    "  }",
    "}",
    "```",
    "",
  ].join("\n");
}
