import Head from "next/head";
import Image from "next/image";
import { NextParticles } from "@tsparticles/nextjs";
import styles from "../styles/Home.module.css";
import { useCallback, useMemo, useRef } from "react";

export default function Home() {
  const containerRef = useRef(null);

  const particlesLoaded = useCallback(
    container => {
      containerRef.current = container;

      globalThis.particlesContainer = container;
    },
    [containerRef],
  );

  const options = useMemo(
    () => ({
      fullScreen: {
        zIndex: -1,
      },
      particles: {
        number: {
          value: 100,
        },
        links: {
          enable: true,
        },
        move: {
          enable: true,
        },
        size: {
          value: 3,
        },
      },
      themes: [
        {
          name: "light",
          default: {
            value: true,
            auto: true,
            mode: "light",
          },
          options: {
            background: {
              color: "#ffffff",
            },
            particles: {
              paint: {
                fill: {
                  color: {
                    value: "#000000",
                  },
                  enable: true,
                },
              },
              links: {
                color: "#000000",
              },
            },
          },
        },
        {
          name: "dark",
          default: {
            value: true,
            auto: true,
            mode: "dark",
          },
          options: {
            background: {
              color: "#000000",
            },
            particles: {
              paint: {
                fill: {
                  color: {
                    value: "#ffffff",
                  },
                  enable: true,
                },
              },
              links: {
                color: "#ffffff",
              },
            },
          },
        },
      ],
    }),
    [],
  );

  const lightTheme = useCallback(() => {
    containerRef.current?.loadTheme("light");
  }, []);

  const darkTheme = useCallback(() => {
    containerRef.current?.loadTheme("dark");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>
        <div>
          <button onClick={lightTheme}>Light</button>
          <button onClick={darkTheme}>Dark</button>
        </div>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <NextParticles id="tsparticles" options={options} particlesLoaded={particlesLoaded} />
    </div>
  );
}
