import { Engine } from "./engine";
import type { IOptions } from "./Options/Interfaces/IOptions";
import type { RecursivePartial } from "./Types/RecursivePartial";

/**
 * The exposed tsParticles instance
 */
const tsParticles = new Engine();

tsParticles.init();

export * from "./Core/Utils/Circle";
export * from "./Core/Utils/CircleWarp";
export * from "./Core/Utils/Constants";
export * from "./Core/Utils/EventListeners";
export * from "./Core/Utils/ExternalInteractorBase";
export * from "./Core/Utils/FrameManager";
export * from "./Core/Utils/InteractionManager";
export * from "./Core/Utils/ParticlesInteractorBase";
export * from "./Core/Utils/Plugins";
export * from "./Core/Utils/Point";
export * from "./Core/Utils/QuadTree";
export * from "./Core/Utils/Range";
export * from "./Core/Utils/Rectangle";
export * from "./Core/Utils/Vector";
export * from "./Core/Utils/Vector3d";
export * from "./Core/Canvas";
export * from "./Core/Container";
export * from "./Core/Loader";
export * from "./Core/Particle";
export * from "./Core/Particles";
export * from "./Core/Retina";
export * from "./Options/Classes/AnimatableColor";
export * from "./Options/Classes/Gradients/AnimatableGradient";
export * from "./Options/Classes/Gradients/AnimatableGradientColor";
export * from "./Options/Classes/Gradients/GradientAngle";
export * from "./Options/Classes/Gradients/GradientAngleAnimation";
export * from "./Options/Classes/Gradients/GradientColorOpacity";
export * from "./Options/Classes/Gradients/GradientColorOpacityAnimation";
export * from "./Options/Classes/AnimationOptions";
export * from "./Options/Classes/Background/Background";
export * from "./Options/Classes/BackgroundMask/BackgroundMask";
export * from "./Options/Classes/BackgroundMask/BackgroundMaskCover";
export * from "./Options/Classes/ColorAnimation";
export * from "./Options/Classes/FullScreen/FullScreen";
export * from "./Options/Classes/HslAnimation";
export * from "./Options/Classes/Interactivity/Events/ClickEvent";
export * from "./Options/Classes/Interactivity/Events/DivEvent";
export * from "./Options/Classes/Interactivity/Events/ClickEvent";
export * from "./Options/Classes/Interactivity/Events/DivEvent";
export * from "./Options/Classes/Interactivity/Events/Events";
export * from "./Options/Classes/Interactivity/Events/HoverEvent";
export * from "./Options/Classes/Interactivity/Events/Parallax";
export * from "./Options/Classes/Interactivity/Interactivity";
export * from "./Options/Classes/Interactivity/Modes/Attract";
export * from "./Options/Classes/Interactivity/Modes/Bounce";
export * from "./Options/Classes/Interactivity/Modes/Bubble";
export * from "./Options/Classes/Interactivity/Modes/BubbleBase";
export * from "./Options/Classes/Interactivity/Modes/BubbleDiv";
export * from "./Options/Classes/Interactivity/Modes/Connect";
export * from "./Options/Classes/Interactivity/Modes/ConnectLinks";
export * from "./Options/Classes/Interactivity/Modes/Grab";
export * from "./Options/Classes/Interactivity/Modes/GrabLinks";
export * from "./Options/Classes/Interactivity/Modes/Light";
export * from "./Options/Classes/Interactivity/Modes/LightArea";
export * from "./Options/Classes/Interactivity/Modes/LightGradient";
export * from "./Options/Classes/Interactivity/Modes/LightShadow";
export * from "./Options/Classes/Interactivity/Modes/Modes";
export * from "./Options/Classes/Interactivity/Modes/Push";
export * from "./Options/Classes/Interactivity/Modes/Remove";
export * from "./Options/Classes/Interactivity/Modes/Repulse";
export * from "./Options/Classes/Interactivity/Modes/RepulseBase";
export * from "./Options/Classes/Interactivity/Modes/RepulseDiv";
export * from "./Options/Classes/Interactivity/Modes/Slow";
export * from "./Options/Classes/Interactivity/Modes/Trail";
export * from "./Options/Classes/ManualParticle";
export * from "./Options/Classes/Motion/Motion";
export * from "./Options/Classes/Motion/MotionReduce";
export * from "./Options/Classes/Options";
export * from "./Options/Classes/OptionsColor";
export * from "./Options/Classes/Particles/Bounce/ParticlesBounce";
export * from "./Options/Classes/Particles/Bounce/ParticlesBounceFactor";
export * from "./Options/Classes/Particles/Collisions/Collisions";
export * from "./Options/Classes/Particles/Collisions/CollisionsOverlap";
export * from "./Options/Classes/Particles/Destroy/Destroy";
export * from "./Options/Classes/Particles/Destroy/Split";
export * from "./Options/Classes/Particles/Destroy/SplitFactor";
export * from "./Options/Classes/Particles/Destroy/SplitRate";
export * from "./Options/Classes/Particles/ParticlesOptions";
export * from "./Options/Classes/Particles/Shadow";
export * from "./Options/Classes/Particles/Stroke";
export * from "./Options/Classes/Particles/Life/Life";
export * from "./Options/Classes/Particles/Life/LifeDelay";
export * from "./Options/Classes/Particles/Life/LifeDuration";
export * from "./Options/Classes/Particles/Links/Links";
export * from "./Options/Classes/Particles/Links/LinksShadow";
export * from "./Options/Classes/Particles/Links/LinksTriangle";
export * from "./Options/Classes/Particles/Move/MoveAttract";
export * from "./Options/Classes/Particles/Move/Move";
export * from "./Options/Classes/Particles/Move/MoveAngle";
export * from "./Options/Classes/Particles/Move/MoveGravity";
export * from "./Options/Classes/Particles/Move/OutModes";
export * from "./Options/Classes/Particles/Move/Path/MovePath";
export * from "./Options/Classes/Particles/Move/Path/MovePathDelay";
export * from "./Options/Classes/Particles/Move/Spin";
export * from "./Options/Classes/Particles/Move/MoveTrail";
export * from "./Options/Classes/Particles/Number/ParticlesNumber";
export * from "./Options/Classes/Particles/Number/ParticlesDensity";
export * from "./Options/Classes/Particles/Opacity/Opacity";
export * from "./Options/Classes/Particles/Opacity/OpacityAnimation";
export * from "./Options/Classes/Particles/Repulse/ParticlesRepulse";
export * from "./Options/Classes/Particles/Rotate/Rotate";
export * from "./Options/Classes/Particles/Rotate/RotateAnimation";
export * from "./Options/Classes/Particles/Shape/Shape";
export * from "./Options/Classes/Particles/Size/Size";
export * from "./Options/Classes/Particles/Size/SizeAnimation";
export * from "./Options/Classes/Particles/ZIndex/ZIndex";
export * from "./Options/Classes/Responsive";
export * from "./Options/Classes/Theme/Theme";
export * from "./Options/Classes/Theme/ThemeDefault";
export * from "./Options/Classes/ValueWithRandom";
export * from "./Utils/CanvasUtils";
export * from "./Utils/ColorUtils";
export * from "./Utils/NumberUtils";
export * from "./Utils/Utils";
export { tsParticles };

/**
 * tsParticles source options alias type, supporting partial objects
 */
export type ISourceOptions = RecursivePartial<IOptions>;
