name: Docs JSON Generation
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

env:
  NX_NO_CLOUD: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run build:ci:json
