name: Renovate (wrappers)

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Renovate
        uses: renovatebot/github-action@v46.1.17
        with:
          configurationFile: renovate-wrappers.json
          token: ${{ secrets.GITHUB_TOKEN }}
