name: Renovate (templates)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Renovate
        uses: renovatebot/github-action@v46.1.20
        with:
          configurationFile: renovate-templates.json
          token: ${{ secrets.RENOVATE_TOKEN }}
