import type { Main } from "tsparticles-core";
import { LifeUpdater } from "tsparticles-core/Updaters/LifeUpdater";
import { OpacityUpdater } from "tsparticles-core/Updaters/OpacityUpdater";
import { AngleUpdater } from "tsparticles-core/Updaters/AngleUpdater";
import { OutOfCanvasUpdater } from "tsparticles-core/Updaters/OutOfCanvasUpdater";
import { loadInteraction as loadExternalAttractInteraction } from "tsparticles-interaction-external-attract";
import { loadInteraction as loadExternalBounceInteraction } from "tsparticles-interaction-external-bounce";
import { loadInteraction as loadExternalBubbleInteraction } from "tsparticles-interaction-external-bubble";
import { loadInteraction as loadExternalConnectInteraction } from "tsparticles-interaction-external-connect";
import { loadInteraction as loadExternalGrabInteraction } from "tsparticles-interaction-external-grab";
import { loadInteraction as loadExternalRepulseInteraction } from "tsparticles-interaction-external-repulse";
import { loadInteraction as loadParticlesAttractInteraction } from "tsparticles-interaction-particles-attract";
import { loadInteraction as loadParticlesCollisionsInteraction } from "tsparticles-interaction-particles-collisions";
import { loadInteraction as loadParticlesLinksInteraction } from "tsparticles-interaction-particles-links";
import { loadInteraction as loadParticlesRepulseInteraction } from "tsparticles-interaction-particles-repulse";
import { loadShape as loadCircleShape } from "tsparticles-shape-circle";
import { loadShape as loadImageShape } from "tsparticles-shape-image";
import { loadShape as loadLineShape } from "tsparticles-shape-line";
import { loadShape as loadPolygonShape } from "tsparticles-shape-polygon";
import { loadShape as loadSquareShape } from "tsparticles-shape-square";
import { loadShape as loadStarShape } from "tsparticles-shape-star";
import { loadShape as loadTextShape } from "tsparticles-shape-text";
import { loadUpdater as loadColorUpdater } from "tsparticles-updater-color";
import { loadUpdater as loadStrokeColorUpdater } from "tsparticles-updater-stroke-color";
import { loadUpdater as loadSizeUpdater } from "tsparticles-updater-size";

export function loadSlim(tsParticles: Main): void {
    tsParticles.addParticleUpdater((container) => new LifeUpdater(container));
    tsParticles.addParticleUpdater((container) => new OpacityUpdater(container));
    tsParticles.addParticleUpdater((container) => new AngleUpdater(container));
    loadColorUpdater(tsParticles);
    loadSizeUpdater(tsParticles);
    loadStrokeColorUpdater(tsParticles);
    tsParticles.addParticleUpdater((container) => new OutOfCanvasUpdater(container));
    loadExternalAttractInteraction(tsParticles);
    loadExternalBounceInteraction(tsParticles);
    loadExternalBubbleInteraction(tsParticles);
    loadExternalConnectInteraction(tsParticles);
    loadExternalGrabInteraction(tsParticles);
    loadExternalRepulseInteraction(tsParticles);
    loadParticlesAttractInteraction(tsParticles);
    loadParticlesCollisionsInteraction(tsParticles);
    loadParticlesRepulseInteraction(tsParticles);
    loadParticlesLinksInteraction(tsParticles);

    loadCircleShape(tsParticles);
    loadImageShape(tsParticles);
    loadLineShape(tsParticles);
    loadPolygonShape(tsParticles);
    loadSquareShape(tsParticles);
    loadStarShape(tsParticles);
    loadTextShape(tsParticles);
}
